<template>
 <view class="trade-inbox"><view class="inbox-heading"><text>{{ t('trade.messages') }}</text><view class="tabs"><view v-for="key in ['all','chat','trade']" :key="key" :class="{selected:tab===key}" @click="switchTab(key)">{{ t('trade.'+key) }}<text v-if="key==='trade'&&noticeCount" class="trade-dot">•</text></view></view></view>
 <view class="inbox-body" :class="{entered}">
  <view v-if="tab==='trade'" class="trade-tools"><view @click="open('notices')"><uni-icons type="notification" size="18" color="var(--bless-primary, #C2A052)"/> {{ t('trade.reminders') }} <text>{{ noticeCount || '' }}</text></view><view @click="open('orders')">{{ t('trade.myTrades') }} ›</view></view>
  <view v-if="tab==='all'&&showInteractions" class="conversation" @click="$emit('interactions')"><view class="avatar-wrap"><view class="fire"><uni-icons type="fire-filled" size="28" color="#fff"/></view><text v-if="interactionUnread" class="unread">{{ badge(interactionUnread) }}</text></view><view class="body"><text class="name">{{ t('inbox.interactions') }}</text><text class="summary">{{ interactionSummary }}</text></view><text class="time">{{ interactionDate }}</text></view>
  <view v-if="tab!=='trade'&&isAdmin&&requestCount" class="conversation" @click="$emit('reviews')"><view class="avatar-wrap"><view class="fire"><uni-icons type="checkmarkempty" size="26" color="#fff"/></view><text class="unread">{{ badge(requestCount) }}</text></view><view class="body"><text class="name">{{ t('inbox.pendingRequests') }}</text></view></view>
  <view v-for="item in items" :key="item.kind+'-'+item.id" class="conversation" @click="openItem(item)"><view class="avatar-wrap"><GroupAvatar v-if="item.kind==='group'" :avatar-url="item.avatar_url" :members="item.members||[]" :size="48"/><image v-else class="avatar" :src="item.peer_avatar||'/static/logo.png'" mode="aspectFill"/><text v-if="Number(item.unread_count)>0" class="unread">{{ badge(item.unread_count) }}</text></view><view class="body"><view class="name-line"><text class="name">{{ item.kind==='group'?presentGroupName(item.name):item.peer_name }}</text><text v-if="item.kind==='trade'" class="tag">{{ t('trade.trade') }}</text></view><text v-if="item.kind==='trade'" class="product-title">{{ item.title }}</text><text class="summary">{{ item.kind==='trade' ? (item.last_kind==='system'?t('trade.'+item.last_message):item.last_kind==='image'?t('trade.image'):item.last_message||t('trade.consulting')) : item.last_message||t('inbox.noMessages') }}</text><text v-if="item.order_status" class="status">{{ t('trade.'+item.order_status) }}</text></view><view class="right"><text class="time">{{ formatConversationTime(item.last_at||item.last_message_at||item.updated_at) }}</text><image v-if="item.kind==='trade'&&item.images?.[0]" :src="item.images[0]" class="thumb" mode="aspectFill"/></view></view>
  <view v-if="error" class="empty" @click="$emit('retry')">{{ t('trade.failed') }} · {{ t('trade.retry') }}</view><view v-else-if="!items.length&&tab!=='all'" class="empty">{{ t('trade.empty') }}</view>
 </view></view>
</template>
<script setup>
import {computed,ref,watch,onMounted,onBeforeUnmount} from 'vue'
import {onShow} from '@dcloudio/uni-app'
import GroupAvatar from '@/components/chat/GroupAvatar.vue'
import {t} from '@/utils/localeRuntime.js'
import {presentGroupName} from '@/utils/chatGroupPresentation.js'
import {formatConversationTime} from '@/utils/chatMessagePresentation.js'
import {tradeRoute} from '@/api/marketTrades.js'
const props=defineProps({groups:Array,trades:Array,search:String,showInteractions:Boolean,interactionUnread:Number,interactionSummary:String,interactionDate:String,isAdmin:Boolean,requestCount:Number,error:Boolean,noticeCount:Number})
const emit=defineEmits(['interactions','reviews','group','retry'])
const tab=ref('all'),entered=ref(false);let timer,transitioning=false,duration=140
// #ifdef H5
if(window.matchMedia?.('(prefers-reduced-motion: reduce)').matches)duration=0
// #endif
const items=computed(()=>{const list=[...(tab.value!=='trade'?(props.groups||[]).map(g=>({...g,kind:'group'})):[]),...(tab.value!=='chat'?(props.trades||[]).map(g=>({...g,kind:'trade'})):[])];const q=(props.search||'').trim().toLowerCase();return list.filter(v=>!q||[v.name,v.peer_name,v.title,v.last_message].some(x=>String(x||'').toLowerCase().includes(q))).sort((a,b)=>new Date(b.last_at||b.last_message_at||b.updated_at||0)-new Date(a.last_at||a.last_message_at||a.updated_at||0))})
function badge(v){return Number(v)>99?'99+':v}
function open(mode){uni.navigateTo({url:tradeRoute(mode)})}
function openItem(item){if(item.kind==='group')emit('group',item.id);else uni.navigateTo({url:tradeRoute('chat',item.id)})}
function enter(){clearTimeout(timer);entered.value=false;timer=setTimeout(()=>{entered.value=true},duration?24:0)}
function switchTab(key){if(tab.value===key||transitioning)return;transitioning=true;entered.value=false;clearTimeout(timer);timer=setTimeout(()=>{tab.value=key;timer=setTimeout(()=>{entered.value=true;transitioning=false},duration?24:0)},duration)}
let firstItems=false;watch(()=>items.value.length,count=>{if(count&&!firstItems){firstItems=true;enter()}});onMounted(enter);onShow(enter);onBeforeUnmount(()=>clearTimeout(timer))
</script>
<style scoped>
.trade-inbox{margin:8px 12px 110px;padding:16px 10px 12px;border:1px solid rgba(255,255,255,.9);border-radius:28px;background:#f8f7f5}.inbox-heading{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap;padding:0 6px 16px;font-size:20px;font-weight:600}.tabs{display:flex;gap:6px;font-size:12px;font-weight:500}.tabs>view{padding:8px 13px;border-radius:22px;background:#eee}.tabs>.selected{background:var(--bless-primary, #C2A052)}.inbox-body{opacity:0;transform:translateY(12px);transition:opacity 180ms ease-out,transform 220ms cubic-bezier(.23,1,.32,1)}.inbox-body.entered{opacity:1;transform:translateY(0)}.conversation{display:flex;align-items:center;gap:11px;background:#fff;border-radius:19px;padding:14px 11px;margin-bottom:9px;min-height:56px}.avatar-wrap{position:relative;flex-shrink:0}.avatar,.fire{width:48px;height:48px;border-radius:50%}.fire{background:var(--bless-primary, #C2A052);display:flex;align-items:center;justify-content:center}.unread{position:absolute;right:-5px;top:-5px;background:var(--bless-primary, #C2A052);border:2px solid #fff;border-radius:20px;min-width:17px;height:17px;padding:0 2px;line-height:17px;text-align:center;font-size:10px;color:#292825}.body{flex:1;min-width:0}.name-line{display:flex;align-items:center;gap:5px}.name{font-size:15px;font-weight:600;overflow:hidden;white-space:nowrap;text-overflow:ellipsis}.tag{background:var(--bless-soft, #F1E4BD);color:var(--bless-text, #775E25);font-size:10px;padding:2px 5px;border-radius:6px;flex-shrink:0}.summary,.product-title{display:block;font-size:12px;overflow:hidden;white-space:nowrap;text-overflow:ellipsis;line-height:1.7;margin-top:3px}.summary{color:#a09d97}.product-title{color:#777}.status{display:block;font-size:11px;color:var(--bless-text, #775E25);margin-top:3px}.time{color:#aaa;font-size:10px;max-width:64px}.right{display:flex;flex-direction:column;align-items:flex-end;gap:7px;flex-shrink:0}.thumb{width:38px;height:38px;border-radius:8px}.trade-tools{display:flex;flex-wrap:wrap;justify-content:space-between;gap:10px;font-size:12px;color:var(--bless-text, #775E25);padding:0 6px 16px}.trade-tools>view{display:flex;align-items:center;gap:5px}.empty{text-align:center;padding:25px;color:#999;font-size:13px}@media(prefers-reduced-motion:reduce){.inbox-body{transition:none;transform:none}}
</style>

<style scoped>.trade-dot{color:var(--bless-text, #775E25);margin-left:3px}</style>
