import { currentLocale } from './localeRuntime.js'

// The account drawer and binding pages share one vocabulary across all supported locales.
const messages = {
  'zh-Hans': {
    accountTitle: '个人中心', accountSecurity: '账号与登录', email: '电子邮箱', phone: '手机号码', bound: '已绑定', unbound: '未绑定', bind: '绑定', manage: '管理', language: '语言', terms: '用户服务协议', privacy: '隐私政策', cancelAccount: '注销账号', logout: '退出登录', cancelConfirmTitle: '注销账号？', cancelConfirmContent: '注销后将无法登录此账号，请谨慎操作。', confirm: '确认', cancel: '取消', retry: '重试', loadError: '加载失败，请重试',
    emailTitle: '绑定电子邮箱', emailHeroTitle: '为账号新增邮箱登录', emailHeroBody: '填写邮箱、验证码并设置密码后，可用此邮箱登录当前账号', phoneTitle: '绑定手机号码', phoneHeroTitle: '为账号新增手机登录', phoneHeroBody: '绑定后，可用手机验证码登录当前账号', countryRegion: '国家／地区', emailAddress: '电子邮箱', phoneNumber: '手机号码', verificationCode: '验证码', sendCode: '查看验证码', emailPlaceholder: '请输入电子邮箱', phonePlaceholder: '请输入手机号码', codePlaceholder: '请输入 6 位验证码', password: '设置登录密码', passwordConfirm: '确认登录密码', passwordPlaceholder: '请输入密码', passwordConfirmPlaceholder: '请再次输入密码', passwordHint: '8–20 个字符，数字、大写字母、小写字母、符号任两种组成', confirmBinding: '确认绑定', bindingNote: '绑定至当前账号，不会建立新账号', codeReady: '验证码：666666', codeUnavailable: '当前环境暂不支持验证码', invalidEmail: '请输入有效的电子邮箱', invalidPhone: '请输入有效的手机号码', invalidCode: '请输入 6 位验证码', invalidPassword: '密码须为 8–20 位，且包含至少两类字符', passwordMismatch: '两次输入的密码不一致', alreadyBound: '此账号已绑定', bindSuccess: '绑定成功', bindFailed: '绑定失败，请重试', bindingUnavailable: '当前环境暂不支持绑定', identityExists: '该邮箱或手机号已被其他账号使用', loginNotAvailable: '此登录方式暂不可用', loading: '正在加载…', processing: '处理中…', emailBoundTitle: '邮箱登录已启用', phoneBoundTitle: '手机登录已启用', currentIdentity: '当前账号', emailLocked: '此邮箱已关联当前账号，请验证后设置登录密码', showPassword: '显示密码', hidePassword: '隐藏密码'
  },
  'zh-Hant': {
    accountTitle: '個人中心', accountSecurity: '帳號與登入', email: '電子郵件', phone: '手機號碼', bound: '已綁定', unbound: '未綁定', bind: '綁定', manage: '管理', language: '語言', terms: '使用者服務協議', privacy: '隱私權政策', cancelAccount: '註銷帳號', logout: '登出', cancelConfirmTitle: '註銷帳號？', cancelConfirmContent: '註銷後將無法登入此帳號，請謹慎操作。', confirm: '確認', cancel: '取消', retry: '重試', loadError: '載入失敗，請重試',
    emailTitle: '綁定電子郵件', emailHeroTitle: '為帳號新增電子郵件登入', emailHeroBody: '填寫電子郵件、驗證碼並設定密碼後，可用此電子郵件登入目前帳號', phoneTitle: '綁定手機號碼', phoneHeroTitle: '為帳號新增手機登入', phoneHeroBody: '綁定後，可用手機驗證碼登入目前帳號', countryRegion: '國家／地區', emailAddress: '電子郵件', phoneNumber: '手機號碼', verificationCode: '驗證碼', sendCode: '查看驗證碼', emailPlaceholder: '請輸入電子郵件', phonePlaceholder: '請輸入手機號碼', codePlaceholder: '請輸入 6 位驗證碼', password: '設定登入密碼', passwordConfirm: '確認登入密碼', passwordPlaceholder: '請輸入密碼', passwordConfirmPlaceholder: '請再次輸入密碼', passwordHint: '8–20 個字元，數字、大寫字母、小寫字母、符號任兩種組成', confirmBinding: '確認綁定', bindingNote: '綁定至目前帳號，不會建立新帳號', codeReady: '驗證碼：666666', codeUnavailable: '目前環境暫不支援驗證碼', invalidEmail: '請輸入有效的電子郵件', invalidPhone: '請輸入有效的手機號碼', invalidCode: '請輸入 6 位驗證碼', invalidPassword: '密碼須為 8–20 位，且包含至少兩類字元', passwordMismatch: '兩次輸入的密碼不一致', alreadyBound: '此帳號已綁定', bindSuccess: '綁定成功', bindFailed: '綁定失敗，請重試', bindingUnavailable: '目前環境暫不支援綁定', identityExists: '此電子郵件或手機號碼已被其他帳號使用', loginNotAvailable: '此登入方式暫不可用', loading: '正在載入…', processing: '處理中…', emailBoundTitle: '電子郵件登入已啟用', phoneBoundTitle: '手機登入已啟用', currentIdentity: '目前帳號', emailLocked: '此電子郵件已關聯目前帳號，請驗證後設定登入密碼', showPassword: '顯示密碼', hidePassword: '隱藏密碼'
  },
  en: {
    accountTitle: 'Account', accountSecurity: 'Account & sign-in', email: 'Email', phone: 'Phone number', bound: 'Linked', unbound: 'Not linked', bind: 'Link', manage: 'Manage', language: 'Language', terms: 'Terms of Service', privacy: 'Privacy Policy', cancelAccount: 'Delete account', logout: 'Log out', cancelConfirmTitle: 'Delete this account?', cancelConfirmContent: 'You will no longer be able to sign in to this account. Please proceed carefully.', confirm: 'Confirm', cancel: 'Cancel', retry: 'Retry', loadError: 'Could not load. Try again.',
    emailTitle: 'Link email', emailHeroTitle: 'Add email sign-in', emailHeroBody: 'Enter an email, verification code, and password to add email sign-in to this account', phoneTitle: 'Link phone number', phoneHeroTitle: 'Add phone sign-in', phoneHeroBody: 'After linking, use a phone verification code to sign in to this account', countryRegion: 'Country / region', emailAddress: 'Email', phoneNumber: 'Phone number', verificationCode: 'Verification code', sendCode: 'View code', emailPlaceholder: 'Enter your email', phonePlaceholder: 'Enter your phone number', codePlaceholder: 'Enter the 6-digit code', password: 'Set sign-in password', passwordConfirm: 'Confirm sign-in password', passwordPlaceholder: 'Enter password', passwordConfirmPlaceholder: 'Enter password again', passwordHint: '8–20 characters with at least two of: numbers, uppercase, lowercase, symbols', confirmBinding: 'Confirm linking', bindingNote: 'Linked to this account; no new account will be created', codeReady: 'Code: 666666', codeUnavailable: 'Verification codes are unavailable here', invalidEmail: 'Enter a valid email', invalidPhone: 'Enter a valid phone number', invalidCode: 'Enter a 6-digit code', invalidPassword: 'Use 8–20 characters from at least two character types', passwordMismatch: 'Passwords do not match', alreadyBound: 'Already linked to this account', bindSuccess: 'Linked successfully', bindFailed: 'Could not link. Try again.', bindingUnavailable: 'Linking is unavailable here', identityExists: 'This email or phone is used by another account', loginNotAvailable: 'This sign-in method is unavailable', loading: 'Loading…', processing: 'Working…', emailBoundTitle: 'Email sign-in is active', phoneBoundTitle: 'Phone sign-in is active', currentIdentity: 'Current account', emailLocked: 'This email is already on your account. Verify it to set a password.', showPassword: 'Show password', hidePassword: 'Hide password'
  },
  ru: {
    accountTitle: 'Аккаунт', accountSecurity: 'Аккаунт и вход', email: 'Эл. почта', phone: 'Номер телефона', bound: 'Привязано', unbound: 'Не привязано', bind: 'Привязать', manage: 'Управлять', language: 'Язык', terms: 'Условия использования', privacy: 'Политика конфиденциальности', cancelAccount: 'Удалить аккаунт', logout: 'Выйти', cancelConfirmTitle: 'Удалить аккаунт?', cancelConfirmContent: 'После удаления вы не сможете войти в этот аккаунт. Действуйте осторожно.', confirm: 'Подтвердить', cancel: 'Отмена', retry: 'Повторить', loadError: 'Не удалось загрузить. Повторите попытку.',
    emailTitle: 'Привязать эл. почту', emailHeroTitle: 'Добавить вход по эл. почте', emailHeroBody: 'Укажите эл. почту, код подтверждения и пароль для входа в этот аккаунт', phoneTitle: 'Привязать телефон', phoneHeroTitle: 'Добавить вход по телефону', phoneHeroBody: 'После привязки входите в этот аккаунт по коду для телефона', countryRegion: 'Страна / регион', emailAddress: 'Эл. почта', phoneNumber: 'Номер телефона', verificationCode: 'Код подтверждения', sendCode: 'Показать код', emailPlaceholder: 'Введите адрес почты', phonePlaceholder: 'Введите номер телефона', codePlaceholder: 'Введите код из 6 цифр', password: 'Пароль для входа', passwordConfirm: 'Подтвердите пароль', passwordPlaceholder: 'Введите пароль', passwordConfirmPlaceholder: 'Повторите пароль', passwordHint: '8–20 символов минимум двух типов: цифры, заглавные, строчные, знаки', confirmBinding: 'Привязать', bindingNote: 'Привязка к текущему аккаунту без создания нового', codeReady: 'Код: 666666', codeUnavailable: 'Код подтверждения здесь недоступен', invalidEmail: 'Введите действительный адрес почты', invalidPhone: 'Введите действительный номер телефона', invalidCode: 'Введите код из 6 цифр', invalidPassword: 'Пароль: 8–20 символов минимум двух типов', passwordMismatch: 'Пароли не совпадают', alreadyBound: 'Уже привязано к этому аккаунту', bindSuccess: 'Успешно привязано', bindFailed: 'Не удалось привязать. Повторите попытку.', bindingUnavailable: 'Привязка здесь недоступна', identityExists: 'Эта почта или номер заняты другим аккаунтом', loginNotAvailable: 'Этот способ входа недоступен', loading: 'Загрузка…', processing: 'Обработка…', emailBoundTitle: 'Вход по почте активен', phoneBoundTitle: 'Вход по телефону активен', currentIdentity: 'Текущий аккаунт', emailLocked: 'Эта почта уже указана в аккаунте. Подтвердите её и задайте пароль.', showPassword: 'Показать пароль', hidePassword: 'Скрыть пароль'
  },
  ja: {
    accountTitle: 'アカウント', accountSecurity: 'アカウントとログイン', email: 'メール', phone: '電話番号', bound: '連携済み', unbound: '未連携', bind: '連携', manage: '管理', language: '言語', terms: '利用規約', privacy: 'プライバシーポリシー', cancelAccount: 'アカウントを削除', logout: 'ログアウト', cancelConfirmTitle: 'アカウントを削除しますか？', cancelConfirmContent: '削除後はこのアカウントにログインできません。慎重に操作してください。', confirm: '確認', cancel: 'キャンセル', retry: '再試行', loadError: '読み込めませんでした。再試行してください。',
    emailTitle: 'メールを連携', emailHeroTitle: 'メールログインを追加', emailHeroBody: 'メールアドレス、認証コード、パスワードを入力すると、このアカウントにメールでログインできます', phoneTitle: '電話番号を連携', phoneHeroTitle: '電話ログインを追加', phoneHeroBody: '連携後、電話認証コードでこのアカウントにログインできます', countryRegion: '国／地域', emailAddress: 'メール', phoneNumber: '電話番号', verificationCode: '認証コード', sendCode: 'コードを表示', emailPlaceholder: 'メールアドレスを入力', phonePlaceholder: '電話番号を入力', codePlaceholder: '6 桁のコードを入力', password: 'ログインパスワード', passwordConfirm: 'パスワードを確認', passwordPlaceholder: 'パスワードを入力', passwordConfirmPlaceholder: 'もう一度入力', passwordHint: '8～20 文字で数字・大文字・小文字・記号のうち 2 種類以上', confirmBinding: '連携を確認', bindingNote: '現在のアカウントに連携し、新規作成はしません', codeReady: 'コード：666666', codeUnavailable: 'この環境では認証コードを使えません', invalidEmail: '有効なメールアドレスを入力してください', invalidPhone: '有効な電話番号を入力してください', invalidCode: '6 桁のコードを入力してください', invalidPassword: '8～20 文字で 2 種類以上の文字を使ってください', passwordMismatch: 'パスワードが一致しません', alreadyBound: 'このアカウントに連携済みです', bindSuccess: '連携しました', bindFailed: '連携できませんでした。再試行してください。', bindingUnavailable: 'この環境では連携できません', identityExists: 'このメールまたは電話番号は別のアカウントで使用中です', loginNotAvailable: 'このログイン方法は利用できません', loading: '読み込み中…', processing: '処理中…', emailBoundTitle: 'メールログインが有効です', phoneBoundTitle: '電話ログインが有効です', currentIdentity: '現在のアカウント', emailLocked: 'このメールは登録済みです。確認してパスワードを設定してください。', showPassword: 'パスワードを表示', hidePassword: 'パスワードを隠す'
  },
  ko: {
    accountTitle: '계정', accountSecurity: '계정 및 로그인', email: '이메일', phone: '전화번호', bound: '연결됨', unbound: '연결 안 됨', bind: '연결', manage: '관리', language: '언어', terms: '서비스 이용약관', privacy: '개인정보 처리방침', cancelAccount: '계정 삭제', logout: '로그아웃', cancelConfirmTitle: '계정을 삭제할까요?', cancelConfirmContent: '삭제 후 이 계정에 로그인할 수 없습니다. 신중히 진행해 주세요.', confirm: '확인', cancel: '취소', retry: '다시 시도', loadError: '불러오지 못했습니다. 다시 시도해 주세요.',
    emailTitle: '이메일 연결', emailHeroTitle: '이메일 로그인 추가', emailHeroBody: '이메일, 인증 코드, 비밀번호를 입력하면 이 계정에 이메일로 로그인할 수 있습니다', phoneTitle: '전화번호 연결', phoneHeroTitle: '전화 로그인 추가', phoneHeroBody: '연결하면 전화 인증 코드로 이 계정에 로그인할 수 있습니다', countryRegion: '국가 / 지역', emailAddress: '이메일', phoneNumber: '전화번호', verificationCode: '인증 코드', sendCode: '코드 보기', emailPlaceholder: '이메일을 입력하세요', phonePlaceholder: '전화번호를 입력하세요', codePlaceholder: '6자리 코드를 입력하세요', password: '로그인 비밀번호 설정', passwordConfirm: '비밀번호 확인', passwordPlaceholder: '비밀번호를 입력하세요', passwordConfirmPlaceholder: '비밀번호를 다시 입력하세요', passwordHint: '8~20자, 숫자·대문자·소문자·기호 중 2종류 이상', confirmBinding: '연결 확인', bindingNote: '현재 계정에 연결하며 새 계정은 만들지 않습니다', codeReady: '코드: 666666', codeUnavailable: '이 환경에서는 인증 코드를 사용할 수 없습니다', invalidEmail: '올바른 이메일을 입력하세요', invalidPhone: '올바른 전화번호를 입력하세요', invalidCode: '6자리 코드를 입력하세요', invalidPassword: '8~20자, 2종류 이상의 문자를 사용하세요', passwordMismatch: '비밀번호가 일치하지 않습니다', alreadyBound: '이미 이 계정에 연결되었습니다', bindSuccess: '연결되었습니다', bindFailed: '연결하지 못했습니다. 다시 시도하세요.', bindingUnavailable: '이 환경에서는 연결할 수 없습니다', identityExists: '다른 계정에서 사용 중인 이메일 또는 번호입니다', loginNotAvailable: '이 로그인 방법을 사용할 수 없습니다', loading: '불러오는 중…', processing: '처리 중…', emailBoundTitle: '이메일 로그인이 활성화됨', phoneBoundTitle: '전화 로그인이 활성화됨', currentIdentity: '현재 계정', emailLocked: '이 이메일은 이미 계정에 있습니다. 확인 후 비밀번호를 설정하세요.', showPassword: '비밀번호 표시', hidePassword: '비밀번호 숨기기'
  }
}

const statusMessages = {
  'zh-Hans': { emailPasswordRequired: '待设置密码', phoneLoginUnavailable: '手机登录暂不可用', codeIncorrect: '验证码错误', myAccount: '我的账号', bindingHint: '绑定后可使用两种方式登录', back: '返回', cancelAuthTitle: "再次验证身份", cancelAuthHint: "请确认这是您的账号，验证通过后将注销账号。", cancelPasswordLabel: "当前邮箱登录密码", cancelPasswordPlaceholder: "请输入当前密码", cancelCodeLabel: "手机验证码", cancelCodePlaceholder: "请输入 6 位验证码", cancelSubmit: "确认注销账号", cancelVerifyFailed: "验证失败，请检查后重试", cancelPhoneUnavailable: "当前环境无法验证手机号，暂不能注销账号", cancelReauthRequired: "登录已失效，请重新登录后重试" },
  'zh-Hant': { emailPasswordRequired: '待設定密碼', phoneLoginUnavailable: '手機登入暫不可用', codeIncorrect: '驗證碼錯誤', myAccount: '我的帳戶', bindingHint: '綁定後可使用兩種方式登入', back: '返回', cancelAuthTitle: "再次驗證身分", cancelAuthHint: "請確認這是您的帳號，驗證通過後將註銷帳號。", cancelPasswordLabel: "目前電子郵件登入密碼", cancelPasswordPlaceholder: "請輸入目前密碼", cancelCodeLabel: "手機驗證碼", cancelCodePlaceholder: "請輸入 6 位驗證碼", cancelSubmit: "確認註銷帳號", cancelVerifyFailed: "驗證失敗，請檢查後重試", cancelPhoneUnavailable: "目前環境無法驗證手機號碼，暫不能註銷帳號", cancelReauthRequired: "登入已失效，請重新登入後重試" },
  en: { emailPasswordRequired: 'Set a password', phoneLoginUnavailable: 'Phone sign-in unavailable', codeIncorrect: 'Incorrect verification code', myAccount: 'My account', bindingHint: 'Use either method to sign in after linking', back: 'Back', cancelAuthTitle: "Verify your identity", cancelAuthHint: "Confirm this is your account before deleting it.", cancelPasswordLabel: "Current email password", cancelPasswordPlaceholder: "Enter your current password", cancelCodeLabel: "Phone verification code", cancelCodePlaceholder: "Enter the 6-digit code", cancelSubmit: "Delete account", cancelVerifyFailed: "Verification failed. Check and try again.", cancelPhoneUnavailable: "Phone verification is unavailable here. Account deletion is unavailable.", cancelReauthRequired: "Your sign-in has expired. Sign in again and retry." },
  ru: { emailPasswordRequired: 'Нужен пароль', phoneLoginUnavailable: 'Вход по телефону недоступен', codeIncorrect: 'Неверный код подтверждения', myAccount: 'Мой аккаунт', bindingHint: 'После привязки можно входить двумя способами', back: 'Назад', cancelAuthTitle: "Подтвердите личность", cancelAuthHint: "Подтвердите, что это ваш аккаунт, прежде чем удалить его.", cancelPasswordLabel: "Текущий пароль эл. почты", cancelPasswordPlaceholder: "Введите текущий пароль", cancelCodeLabel: "Код подтверждения телефона", cancelCodePlaceholder: "Введите 6-значный код", cancelSubmit: "Удалить аккаунт", cancelVerifyFailed: "Не удалось подтвердить. Проверьте данные и повторите.", cancelPhoneUnavailable: "Подтверждение телефона здесь недоступно. Удаление аккаунта невозможно.", cancelReauthRequired: "Срок входа истёк. Войдите снова и повторите." },
  ja: { emailPasswordRequired: 'パスワード未設定', phoneLoginUnavailable: '電話ログインは利用できません', codeIncorrect: '認証コードが正しくありません', myAccount: 'マイアカウント', bindingHint: '連携後は両方の方法でログインできます', back: '戻る', cancelAuthTitle: "本人確認", cancelAuthHint: "アカウントを削除する前に、ご本人であることを確認します。", cancelPasswordLabel: "現在のメールログインパスワード", cancelPasswordPlaceholder: "現在のパスワードを入力", cancelCodeLabel: "電話認証コード", cancelCodePlaceholder: "6 桁のコードを入力", cancelSubmit: "アカウントを削除", cancelVerifyFailed: "認証できませんでした。確認して再試行してください。", cancelPhoneUnavailable: "電話認証を利用できないため、アカウントを削除できません。", cancelReauthRequired: "ログインの有効期限が切れました。再ログインして再試行してください。" },
  ko: { emailPasswordRequired: '비밀번호 설정 필요', phoneLoginUnavailable: '전화 로그인 사용 불가', codeIncorrect: '인증 코드가 올바르지 않습니다', myAccount: '내 계정', bindingHint: '연결 후 두 가지 방법으로 로그인할 수 있습니다', back: '뒤로', cancelAuthTitle: "본인 확인", cancelAuthHint: "계정을 삭제하기 전에 본인 계정인지 확인합니다.", cancelPasswordLabel: "현재 이메일 로그인 비밀번호", cancelPasswordPlaceholder: "현재 비밀번호를 입력하세요", cancelCodeLabel: "전화 인증 코드", cancelCodePlaceholder: "6자리 코드를 입력하세요", cancelSubmit: "계정 삭제", cancelVerifyFailed: "인증에 실패했습니다. 확인 후 다시 시도하세요.", cancelPhoneUnavailable: "현재 전화 인증을 사용할 수 없어 계정을 삭제할 수 없습니다.", cancelReauthRequired: "로그인이 만료되었습니다. 다시 로그인하고 시도하세요." }
}

const identityChangedMessages = {
  'zh-Hans': '账号绑定状态已变化，请刷新后重试',
  'zh-Hant': '帳號綁定狀態已變更，請重新整理後再試',
  en: 'Account linking has changed. Refresh and try again.',
  ru: 'Статус привязки изменился. Обновите страницу и повторите попытку.',
  ja: '連携状態が変わりました。更新してもう一度お試しください。',
  ko: '계정 연결 상태가 변경되었습니다. 새로고침 후 다시 시도하세요.'
}

const passwordTooLongMessages = {
  'zh-Hans': '密码内容过长，请缩短后重试',
  'zh-Hant': '密碼內容過長，請縮短後再試',
  en: 'Password is too long. Shorten it and try again.',
  ru: 'Пароль слишком длинный. Сократите его и повторите попытку.',
  ja: 'パスワードが長すぎます。短くして再試行してください。',
  ko: '비밀번호가 너무 깁니다. 줄인 후 다시 시도하세요.'
}

export function getAccountBindingMessages(locale = currentLocale.value) {
  const key = messages[locale] ? locale : 'en'
  return { ...messages[key], ...statusMessages[key], identityChanged: identityChangedMessages[key], passwordTooLong: passwordTooLongMessages[key] }
}
