export const blessingDeckMessages = {
  'zh-Hans': { cards: '卡片', list: '列表', cardMode: '切换卡片模式', listMode: '切换列表模式', pass: '不喜欢，跳过', like: '喜欢', swipeHint: '左滑跳过 · 右滑喜欢', saving: '处理中…', viewProfile: '查看完整资料', noPhoto: '暂无照片', previousPhoto: '上一张照片', nextPhoto: '下一张照片', caughtUp: '这一轮已经看完了', emptyHint: '可以切换列表回看，或开启新一轮浏览。', retryHint: '连接出了点问题，请重试。', retry: '重试', newRound: '再看看', moreFailed: '更多资料加载失败，点击重试', likeFailed: '喜欢未能确认，请重试。当前卡片已保留。' },
  'zh-Hant': { cards: '卡片', list: '列表', cardMode: '切換卡片模式', listMode: '切換列表模式', pass: '不喜歡，略過', like: '喜歡', swipeHint: '左滑略過 · 右滑喜歡', saving: '處理中…', viewProfile: '查看完整資料', noPhoto: '暫無照片', previousPhoto: '上一張照片', nextPhoto: '下一張照片', caughtUp: '這一輪已經看完了', emptyHint: '可以切換列表回看，或開始新一輪瀏覽。', retryHint: '連線出了點問題，請重試。', retry: '重試', newRound: '再看看', moreFailed: '更多資料載入失敗，點擊重試', likeFailed: '未能確認喜歡，請重試。目前卡片已保留。' },
  en: { cards: 'Cards', list: 'List', cardMode: 'Switch to cards', listMode: 'Switch to list', pass: 'Pass on profile', like: 'Like profile', swipeHint: 'Left to pass · Right to like', saving: 'Saving…', viewProfile: 'View full profile', noPhoto: 'No photo yet', previousPhoto: 'Previous photo', nextPhoto: 'Next photo', caughtUp: 'All caught up', emptyHint: 'Revisit profiles in the list or start another round.', retryHint: 'Could not connect. Please try again.', retry: 'Retry', newRound: 'Browse again', moreFailed: 'Could not load more. Tap to retry.', likeFailed: 'Could not confirm your like. Your card is still here; please retry.' },
  ru: { cards: 'Карточки', list: 'Список', cardMode: 'Показать карточки', listMode: 'Показать список', pass: 'Пропустить анкету', like: 'Нравится', swipeHint: 'Влево — пропустить · Вправо — нравится', saving: 'Сохранение…', viewProfile: 'Открыть анкету', noPhoto: 'Нет фотографии', previousPhoto: 'Предыдущее фото', nextPhoto: 'Следующее фото', caughtUp: 'Все анкеты просмотрены', emptyHint: 'Вернитесь к списку или начните новый просмотр.', retryHint: 'Нет соединения. Попробуйте ещё раз.', retry: 'Повторить', newRound: 'Смотреть ещё', moreFailed: 'Не удалось загрузить ещё. Нажмите, чтобы повторить.', likeFailed: 'Не удалось подтвердить отметку. Карточка сохранена — повторите попытку.' },
  ja: { cards: 'カード', list: 'リスト', cardMode: 'カード表示に切り替え', listMode: 'リスト表示に切り替え', pass: 'スキップ', like: 'いいね', swipeHint: '左でスキップ · 右でいいね', saving: '処理中…', viewProfile: 'プロフィールを見る', noPhoto: '写真はありません', previousPhoto: '前の写真', nextPhoto: '次の写真', caughtUp: 'すべて確認しました', emptyHint: 'リストで見返すか、もう一度探してみましょう。', retryHint: '接続できませんでした。再試行してください。', retry: '再試行', newRound: 'もう一度見る', moreFailed: '読み込めませんでした。タップして再試行', likeFailed: 'いいねを確認できませんでした。カードはそのままです。再試行してください。' },
  ko: { cards: '카드', list: '목록', cardMode: '카드 보기로 전환', listMode: '목록 보기로 전환', pass: '건너뛰기', like: '좋아요', swipeHint: '왼쪽은 건너뛰기 · 오른쪽은 좋아요', saving: '처리 중…', viewProfile: '전체 프로필 보기', noPhoto: '사진 없음', previousPhoto: '이전 사진', nextPhoto: '다음 사진', caughtUp: '모두 확인했어요', emptyHint: '목록에서 다시 보거나 새로 둘러보세요.', retryHint: '연결할 수 없습니다. 다시 시도해 주세요.', retry: '다시 시도', newRound: '다시 둘러보기', moreFailed: '더 불러오지 못했습니다. 눌러서 다시 시도하세요.', likeFailed: '좋아요를 확인하지 못했습니다. 카드를 유지했으니 다시 시도해 주세요.' }
}

const membershipDeckMessages = {
  'zh-Hans': { rewind: '撤回', quota: '今日剩余：赞 {likes} · 撤回 {rewinds}', unlimited: '无限', quotaLoading: '正在更新今日额度…', rewindFailed: '撤回失败，请重试', likeFailed: '操作未能确认，请重试。当前卡片已保留。', emptyHint: '暂时没有新的推荐。可撤回上一张，或稍后刷新。', searchLocked: '搜索为金会员权益', viewMembership: '查看会员权益', enterGroup: '进入沟通群' },
  'zh-Hant': { rewind: '撤回', quota: '今日剩餘：讚 {likes} · 撤回 {rewinds}', unlimited: '無限', quotaLoading: '正在更新今日額度…', rewindFailed: '撤回失敗，請重試', likeFailed: '未能確認操作，請重試。目前卡片已保留。', emptyHint: '暫時沒有新的推薦。可撤回上一張，或稍後重新整理。', searchLocked: '搜尋為金會員權益', viewMembership: '查看會員權益', enterGroup: '進入溝通群' },
  en: { rewind: 'Rewind', quota: 'Today: {likes} likes · {rewinds} rewinds left', unlimited: 'Unlimited', quotaLoading: 'Updating today’s allowance…', rewindFailed: 'Could not rewind. Please try again.', likeFailed: 'Could not confirm your action. Your card is still here; please retry.', emptyHint: 'No new recommendations yet. Rewind the last card or refresh later.', searchLocked: 'Search is a Gold member benefit', viewMembership: 'View membership', enterGroup: 'Open chat group' },
  ru: { rewind: 'Вернуть', quota: 'Осталось сегодня: {likes} симпатий · {rewinds} возвратов', unlimited: 'Без ограничений', quotaLoading: 'Обновляем лимиты на сегодня…', rewindFailed: 'Не удалось вернуть карточку. Повторите попытку.', likeFailed: 'Не удалось подтвердить действие. Карточка сохранена — повторите попытку.', emptyHint: 'Новых рекомендаций пока нет. Верните последнюю карточку или обновите позже.', searchLocked: 'Поиск доступен с золотым членством', viewMembership: 'Условия членства', enterGroup: 'Открыть групповой чат' },
  ja: { rewind: '元に戻す', quota: '本日の残り：いいね {likes} · 取り消し {rewinds}', unlimited: '無制限', quotaLoading: '本日の利用枠を更新中…', rewindFailed: '元に戻せませんでした。再試行してください。', likeFailed: '操作を確認できませんでした。カードはそのままです。再試行してください。', emptyHint: '新しいおすすめはありません。直前のカードを戻すか、後で更新してください。', searchLocked: '検索はゴールド会員の特典です', viewMembership: '会員特典を見る', enterGroup: 'グループチャットを開く' },
  ko: { rewind: '되돌리기', quota: '오늘 남은 횟수: 좋아요 {likes} · 되돌리기 {rewinds}', unlimited: '무제한', quotaLoading: '오늘의 이용 횟수 업데이트 중…', rewindFailed: '되돌리지 못했습니다. 다시 시도해 주세요.', likeFailed: '작업을 확인하지 못했습니다. 카드를 유지했으니 다시 시도해 주세요.', emptyHint: '새 추천이 없습니다. 마지막 카드를 되돌리거나 나중에 새로 고치세요.', searchLocked: '검색은 골드 회원 혜택입니다', viewMembership: '회원 혜택 보기', enterGroup: '그룹 채팅 열기' }
}
for (const locale of Object.keys(blessingDeckMessages)) Object.assign(blessingDeckMessages[locale], membershipDeckMessages[locale])

const stamps = { 'zh-Hans': ['喜欢', '跳过'], 'zh-Hant': ['喜歡', '略過'], en: ['LIKE', 'PASS'], ru: ['НРАВИТСЯ', 'ПРОПУСТИТЬ'], ja: ['いいね', 'スキップ'], ko: ['좋아요', '건너뛰기'] }
for (const [locale, [stampLike, stampPass]] of Object.entries(stamps)) Object.assign(blessingDeckMessages[locale], { stampLike, stampPass })

const quotaRetry = { 'zh-Hans': '今日额度读取失败，点击重试', 'zh-Hant': '今日額度讀取失敗，點擊重試', en: 'Could not load today’s allowance. Tap to retry.', ru: 'Не удалось загрузить лимиты. Нажмите, чтобы повторить.', ja: '本日の利用枠を読み込めません。タップして再試行', ko: '오늘의 이용 횟수를 불러오지 못했습니다. 눌러서 다시 시도하세요.' }
for (const [locale, message] of Object.entries(quotaRetry)) blessingDeckMessages[locale].quotaRetry = message

const listQuotaMessages = {
 'zh-Hans': ['今日剩余 {count} 赞', '无限赞', '更新中', '点击重试'],
 'zh-Hant': ['今日剩餘 {count} 讚', '無限讚', '更新中', '點擊重試'],
 en: ['{count} likes left today', 'Unlimited likes', 'Updating', 'Retry'],
 ru: ['Сегодня: {count} лайков', 'Безлимитные лайки', 'Обновление', 'Повторить'],
 ja: ['本日残り {count} いいね', 'いいね無制限', '更新中', '再試行'],
 ko: ['오늘 좋아요 {count}회 남음', '무제한 좋아요', '업데이트 중', '다시 시도']
}
for (const [locale, [likesRemaining, unlimitedLikes, quotaLoadingShort, quotaRetryShort]] of Object.entries(listQuotaMessages)) Object.assign(blessingDeckMessages[locale], { likesRemaining, unlimitedLikes, quotaLoadingShort, quotaRetryShort })
