export const groupExitMessages = {
  'zh-Hans': {
    requestAction: '申请退出群聊', requestSubtitle: '由群管理员审核后退出', pendingAction: '退群申请待审核', pendingSubtitle: '通过前仍可正常聊天', rejectedAction: '重新申请退出', rejectedSubtitle: '上次申请未通过，你仍在群聊中', approvalEntry: '退出申请', approvalCount: '{count} 条待审核',
    requestDialogTitle: '申请退出群聊', requestDialogContent: '提交后由其他群管理员审核。通过之前，你仍在群内，可以正常收发消息。', reasonPlaceholder: '给管理员留言（选填）', later: '暂不退出', submit: '提交申请', sentTitle: '正在等待管理员审核', sentContent: '申请已提交。审核结果会通过消息通知你；通过前仍可正常聊天。', gotIt: '知道了', soleAdminTitle: '暂时无法申请退出', soleAdminContent: '当前群没有其他可以审核此申请的管理员。请联系群管理员安排审核人后重试。',
    requestFailed: '提交失败，请稍后重试', statusFailed: '申请状态加载失败', reviewLoadFailed: '退出申请加载失败', noPermission: '你没有审核此群申请的权限', retry: '重试', reviewTitle: '退出申请', pendingHeading: '待处理申请', reviewInfo: '同意后成员才会退出群聊；拒绝后成员仍留在群内。审核结果会通知申请人。', approve: '同意退出', reject: '拒绝', approveDone: '已同意退出，成员已退出群聊', rejectDone: '已拒绝申请，成员仍在群内', reviewFailed: '处理失败，请稍后重试', requestChanged: '申请状态已变化，请刷新后重试', noReason: '未填写留言', applicantFallback: '群成员', appliedAt: '申请退出 · {time}', emptyTitle: '没有待处理的申请', emptyContent: '新的退群申请会显示在这里。', approvedState: '退出申请已通过', cancelledState: '申请已结束', leftGroup: '你已退出该群聊', noMembership: '你已不在该群聊中', backToMessages: '返回消息', notificationRequested: '申请退出群聊，等待你审核', notificationApproved: '你的退群申请已通过', notificationRejected: '你的退群申请未通过'
  },
  'zh-Hant': {
    requestAction: '申請退出群聊', requestSubtitle: '經群管理員審核後退出', pendingAction: '退群申請待審核', pendingSubtitle: '通過前仍可正常聊天', rejectedAction: '重新申請退出', rejectedSubtitle: '上次申請未通過，你仍在群聊中', approvalEntry: '退出申請', approvalCount: '{count} 筆待審核',
    requestDialogTitle: '申請退出群聊', requestDialogContent: '提交後由其他群管理員審核。通過之前，你仍在群內，可以正常收發消息。', reasonPlaceholder: '給管理員留言（選填）', later: '暫不退出', submit: '提交申請', sentTitle: '正在等待管理員審核', sentContent: '申請已提交。審核結果會透過消息通知你；通過前仍可正常聊天。', gotIt: '知道了', soleAdminTitle: '暫時無法申請退出', soleAdminContent: '目前群內沒有其他可審核此申請的管理員。請聯絡群管理員安排審核人後再試。',
    requestFailed: '提交失敗，請稍後重試', statusFailed: '申請狀態載入失敗', reviewLoadFailed: '退出申請載入失敗', noPermission: '你沒有審核此群申請的權限', retry: '重試', reviewTitle: '退出申請', pendingHeading: '待處理申請', reviewInfo: '同意後成員才會退出群聊；拒絕後成員仍留在群內。審核結果會通知申請人。', approve: '同意退出', reject: '拒絕', approveDone: '已同意退出，成員已退出群聊', rejectDone: '已拒絕申請，成員仍在群內', reviewFailed: '處理失敗，請稍後重試', requestChanged: '申請狀態已變更，請重新整理後重試', noReason: '未填寫留言', applicantFallback: '群成員', appliedAt: '申請退出 · {time}', emptyTitle: '沒有待處理的申請', emptyContent: '新的退群申請會顯示在這裡。', approvedState: '退出申請已通過', cancelledState: '申請已結束', leftGroup: '你已退出該群聊', noMembership: '你已不在該群聊中', backToMessages: '返回消息', notificationRequested: '申請退出群聊，等待你審核', notificationApproved: '你的退群申請已通過', notificationRejected: '你的退群申請未通過'
  },
  en: {
    requestAction: 'Request to leave group', requestSubtitle: 'An admin will review your request', pendingAction: 'Exit request pending', pendingSubtitle: 'You can still chat until it is approved', rejectedAction: 'Request to leave again', rejectedSubtitle: 'Your last request was declined; you are still a member', approvalEntry: 'Exit requests', approvalCount: '{count} pending',
    requestDialogTitle: 'Request to leave group', requestDialogContent: 'Another group admin will review your request. You can still send and receive messages until it is approved.', reasonPlaceholder: 'Message to the admins (optional)', later: 'Stay for now', submit: 'Send request', sentTitle: 'Waiting for admin review', sentContent: 'Your request was sent. You will get a message with the result. You can keep chatting until approval.', gotIt: 'Got it', soleAdminTitle: 'Cannot request to leave yet', soleAdminContent: 'No other admin can review this request yet. Ask the group admins to arrange a reviewer, then try again.',
    requestFailed: 'Could not send request. Try again.', statusFailed: 'Could not load request status', reviewLoadFailed: 'Could not load exit requests', noPermission: 'You cannot review requests for this group', retry: 'Retry', reviewTitle: 'Exit requests', pendingHeading: 'Pending requests', reviewInfo: 'Approval removes the member from the group. Rejection keeps them in the group. We will notify the applicant.', approve: 'Approve exit', reject: 'Decline', approveDone: 'Approved. The member has left the group.', rejectDone: 'Declined. The member remains in the group.', reviewFailed: 'Could not process request. Try again.', requestChanged: 'This request changed. Refresh and try again.', noReason: 'No message', applicantFallback: 'Group member', appliedAt: 'Requested exit · {time}', emptyTitle: 'No pending requests', emptyContent: 'New exit requests will appear here.', approvedState: 'Exit request approved', cancelledState: 'Request closed', leftGroup: 'You have left this group', noMembership: 'You are no longer in this group', backToMessages: 'Back to messages', notificationRequested: 'requested to leave the group. Please review', notificationApproved: 'Your request to leave was approved', notificationRejected: 'Your request to leave was declined'
  },
  ru: {
    requestAction: 'Подать заявку на выход', requestSubtitle: 'Выход подтвердит администратор', pendingAction: 'Заявка на выход рассматривается', pendingSubtitle: 'До одобрения можно продолжать общение', rejectedAction: 'Подать заявку снова', rejectedSubtitle: 'Прошлую заявку отклонили; вы всё ещё в группе', approvalEntry: 'Заявки на выход', approvalCount: 'На рассмотрении: {count}',
    requestDialogTitle: 'Подать заявку на выход', requestDialogContent: 'Другой администратор рассмотрит заявку. До одобрения вы остаётесь в группе и можете отправлять и получать сообщения.', reasonPlaceholder: 'Сообщение администраторам (необязательно)', later: 'Остаться', submit: 'Отправить заявку', sentTitle: 'Ожидание решения администратора', sentContent: 'Заявка отправлена. О решении придёт уведомление; до одобрения можно продолжать общение.', gotIt: 'Понятно', soleAdminTitle: 'Пока нельзя выйти', soleAdminContent: 'В группе пока нет другого администратора, который может рассмотреть заявку. Попросите администраторов назначить такого участника.',
    requestFailed: 'Не удалось отправить заявку. Повторите попытку.', statusFailed: 'Не удалось загрузить статус заявки', reviewLoadFailed: 'Не удалось загрузить заявки', noPermission: 'Вы не можете рассматривать заявки этой группы', retry: 'Повторить', reviewTitle: 'Заявки на выход', pendingHeading: 'Ожидают решения', reviewInfo: 'После одобрения участник выйдет из группы. При отказе он останется. Заявитель получит уведомление.', approve: 'Одобрить выход', reject: 'Отклонить', approveDone: 'Выход одобрен: участник покинул группу', rejectDone: 'Заявка отклонена: участник остался в группе', reviewFailed: 'Не удалось обработать заявку. Повторите попытку.', requestChanged: 'Статус заявки изменился. Обновите список.', noReason: 'Без сообщения', applicantFallback: 'Участник группы', appliedAt: 'Заявка на выход · {time}', emptyTitle: 'Нет заявок', emptyContent: 'Новые заявки на выход появятся здесь.', approvedState: 'Заявка на выход одобрена', cancelledState: 'Заявка закрыта', leftGroup: 'Вы покинули группу', noMembership: 'Вы больше не состоите в этой группе', backToMessages: 'К сообщениям', notificationRequested: 'подал(а) заявку на выход из группы', notificationApproved: 'Ваш выход из группы одобрен', notificationRejected: 'Вашу заявку на выход отклонили'
  },
  ja: {
    requestAction: 'グループからの退出を申請', requestSubtitle: '管理者の承認後に退出できます', pendingAction: '退出申請は審査待ちです', pendingSubtitle: '承認されるまではチャットできます', rejectedAction: 'もう一度退出を申請', rejectedSubtitle: '前回の申請は却下され、まだグループに参加中です', approvalEntry: '退出申請', approvalCount: '審査待ち {count} 件',
    requestDialogTitle: 'グループからの退出を申請', requestDialogContent: '他のグループ管理者が審査します。承認されるまではグループに残り、メッセージを送受信できます。', reasonPlaceholder: '管理者へのメッセージ（任意）', later: '今は退出しない', submit: '申請を送信', sentTitle: '管理者の審査待ち', sentContent: '申請を送信しました。結果はメッセージでお知らせします。承認まではチャットできます。', gotIt: 'わかりました', soleAdminTitle: 'まだ退出を申請できません', soleAdminContent: '現在、この申請を審査できる他の管理者がいません。管理者に審査担当者を用意してもらってから再度お試しください。',
    requestFailed: '申請を送信できませんでした。再度お試しください。', statusFailed: '申請状況を読み込めませんでした', reviewLoadFailed: '退出申請を読み込めませんでした', noPermission: 'このグループの申請を審査する権限がありません', retry: '再試行', reviewTitle: '退出申請', pendingHeading: '審査待ちの申請', reviewInfo: '承認するとメンバーはグループから退出します。却下すると残ります。結果は申請者に通知されます。', approve: '退出を承認', reject: '却下', approveDone: '承認しました。メンバーは退出しました。', rejectDone: '却下しました。メンバーはグループに残ります。', reviewFailed: '処理できませんでした。再度お試しください。', requestChanged: '申請状況が変わりました。更新して再試行してください。', noReason: 'メッセージなし', applicantFallback: 'グループメンバー', appliedAt: '退出申請 · {time}', emptyTitle: '審査待ちの申請はありません', emptyContent: '新しい退出申請はここに表示されます。', approvedState: '退出申請が承認されました', cancelledState: '申請は終了しました', leftGroup: 'このグループから退出しました', noMembership: 'このグループには参加していません', backToMessages: 'メッセージに戻る', notificationRequested: 'グループからの退出を申請しました。審査してください', notificationApproved: '退出申請が承認されました', notificationRejected: '退出申請が却下されました'
  },
  ko: {
    requestAction: '그룹 채팅 나가기 신청', requestSubtitle: '관리자 승인 후 나갈 수 있어요', pendingAction: '나가기 신청 검토 중', pendingSubtitle: '승인 전에는 계속 대화할 수 있어요', rejectedAction: '다시 나가기 신청', rejectedSubtitle: '지난 신청이 거절되어 아직 그룹에 있어요', approvalEntry: '나가기 신청', approvalCount: '검토 대기 {count}건',
    requestDialogTitle: '그룹 채팅 나가기 신청', requestDialogContent: '다른 그룹 관리자가 신청을 검토합니다. 승인 전에는 그룹에 남아 메시지를 주고받을 수 있어요.', reasonPlaceholder: '관리자에게 남길 말 (선택)', later: '지금은 머무르기', submit: '신청 보내기', sentTitle: '관리자 검토 대기 중', sentContent: '신청을 보냈어요. 결과는 메시지로 알려드립니다. 승인 전까지 계속 대화할 수 있어요.', gotIt: '확인', soleAdminTitle: '아직 나가기를 신청할 수 없어요', soleAdminContent: '현재 이 신청을 검토할 다른 관리자가 없어요. 그룹 관리자에게 검토 담당자를 마련해 달라고 요청한 뒤 다시 시도해 주세요.',
    requestFailed: '신청을 보내지 못했어요. 다시 시도해 주세요.', statusFailed: '신청 상태를 불러오지 못했어요', reviewLoadFailed: '나가기 신청을 불러오지 못했어요', noPermission: '이 그룹의 신청을 검토할 권한이 없어요', retry: '다시 시도', reviewTitle: '나가기 신청', pendingHeading: '검토 대기 신청', reviewInfo: '승인하면 멤버가 그룹에서 나갑니다. 거절하면 그룹에 남습니다. 결과는 신청자에게 알려드립니다.', approve: '나가기 승인', reject: '거절', approveDone: '승인했어요. 멤버가 그룹에서 나갔습니다.', rejectDone: '거절했어요. 멤버는 그룹에 남습니다.', reviewFailed: '처리하지 못했어요. 다시 시도해 주세요.', requestChanged: '신청 상태가 변경됐어요. 새로고침 후 다시 시도해 주세요.', noReason: '남긴 말 없음', applicantFallback: '그룹 멤버', appliedAt: '나가기 신청 · {time}', emptyTitle: '대기 중인 신청이 없어요', emptyContent: '새로운 나가기 신청이 여기에 표시됩니다.', approvedState: '나가기 신청이 승인됐어요', cancelledState: '신청이 종료됐어요', leftGroup: '이 그룹에서 나갔어요', noMembership: '더 이상 이 그룹의 멤버가 아니에요', backToMessages: '메시지로 돌아가기', notificationRequested: '그룹 나가기를 신청했어요. 검토해 주세요', notificationApproved: '그룹 나가기 신청이 승인됐어요', notificationRejected: '그룹 나가기 신청이 거절됐어요'
  }
}
