const keys = ['antiqueTitle','title','live','scheduled','ended','current','starts','ends','startPrice','increment','info','description','records','era','material','dimensions','condition','restoration','provenance','usageDuration','functionality','accessories','location','delivery','sellerProvided','bid','contact','minimum','bidNote','confirmBid','you','bidder','noBids','invalidBid','bidSuccess','ownBid','bidChanged']
const values = {
'zh-Hans':['古董详情','商品详情','拍卖中','尚未开始','已结束','当前价','距开始','距结束','起拍价','每次加价','商品资料','商品描述','出价记录','年代','材质','尺寸','品相 / 成色','修复情况','来源说明','使用时长','功能状态','随附配件','所在地','交易方式','资料由卖家提供','参与出价','联系卖家','最低出价','请按加价幅度出价。本阶段仅记录出价，暂不收款。','确认出价','我','竞拍者','暂无出价','请输入有效金额','出价已记录','不能对自己的商品出价','出价未成功，请查看最新价格和加价幅度后重试'],
'zh-Hant':['古董詳情','商品詳情','拍賣中','尚未開始','已結束','目前價格','距開始','距結束','起拍價','每次加價','商品資料','商品描述','出價紀錄','年代','材質','尺寸','品相 / 成色','修復情況','來源說明','使用時長','功能狀態','隨附配件','所在地','交易方式','資料由賣家提供','參與出價','聯絡賣家','最低出價','請按加價幅度出價。本階段僅記錄出價，暫不收款。','確認出價','我','競拍者','暫無出價','請輸入有效金額','出價已記錄','不能對自己的商品出價','出價未成功，請查看最新價格和加價幅度後重試'],
en:['Antique details','Item details','Live auction','Upcoming','Ended','Current bid','Starts in','Ends in','Starting price','Bid increment','Item information','Description','Bid history','Period','Material','Dimensions','Condition','Restoration','Provenance','Time used','Working condition','Accessories','Location','Delivery','Information provided by the seller','Place a bid','Contact seller','Minimum bid','Bid in the specified increments. Bids are recorded only; no payments are collected yet.','Confirm bid','You','Bidder','No bids yet','Enter a valid amount','Bid recorded','You cannot bid on your own item','Bid unsuccessful. Check the current price and increment, then retry.'],
ru:['Антиквариат','О товаре','Торги идут','Ожидается','Завершено','Текущая ставка','До начала','До окончания','Начальная цена','Шаг ставки','Сведения о товаре','Описание','История ставок','Период','Материал','Размеры','Состояние','Реставрация','Происхождение','Срок использования','Работоспособность','Комплектация','Местоположение','Доставка','Сведения предоставлены продавцом','Сделать ставку','Связаться с продавцом','Минимальная ставка','Соблюдайте шаг ставки. На этом этапе ставки только записываются, оплата не взимается.','Подтвердить ставку','Вы','Участник','Ставок пока нет','Введите корректную сумму','Ставка записана','Нельзя делать ставку на свой товар','Ставка не принята. Проверьте текущую цену и шаг ставки.'],
ja:['アンティーク詳細','商品詳細','入札受付中','開始前','終了','現在価格','開始まで','終了まで','開始価格','入札単位','商品情報','商品説明','入札履歴','年代','素材','サイズ','状態','修復歴','入手経緯','使用期間','動作状態','付属品','所在地','受渡方法','出品者提供の情報です','入札する','出品者に連絡','最低入札額','指定の単位で入札してください。現段階は入札記録のみで、決済は行いません。','入札を確定','あなた','入札者','入札はまだありません','有効な金額を入力してください','入札を記録しました','自分の商品には入札できません','入札できませんでした。現在価格と入札単位をご確認ください。'],
ko:['골동품 상세','상품 상세','경매 진행 중','시작 전','종료','현재 가격','시작까지','종료까지','시작 가격','입찰 단위','상품 정보','상품 설명','입찰 내역','연대','재질','크기','상태','복원 여부','출처','사용 기간','작동 상태','구성품','지역','거래 방법','판매자가 제공한 정보입니다','입찰하기','판매자 연락','최소 입찰 금액','입찰 단위를 지켜 주세요. 현재는 입찰만 기록하며 결제는 진행하지 않습니다.','입찰 확인','나','입찰자','아직 입찰이 없습니다','올바른 금액을 입력해 주세요','입찰이 기록되었습니다','본인 상품에는 입찰할 수 없습니다','입찰하지 못했습니다. 현재 가격과 입찰 단위를 확인해 주세요.']
}
export const marketDetailMessages = Object.fromEntries(Object.entries(values).map(([locale, list]) => [locale, Object.fromEntries(keys.map((key,index)=>[key,list[index]]))]))

const dayCountdown = { 'zh-Hans': '{days}天 {time}', 'zh-Hant': '{days}天 {time}', en: '{days}d {time}', ru: '{days}д {time}', ja: '{days}日 {time}', ko: '{days}일 {time}' }
for (const locale of Object.keys(marketDetailMessages)) marketDetailMessages[locale].dayCountdown = dayCountdown[locale]
const bidCount = { 'zh-Hans': '{count}次出价', 'zh-Hant': '{count}次出價', en: '{count} bids', ru: 'Ставок: {count}', ja: '入札{count}件', ko: '입찰 {count}회' }
for (const locale of Object.keys(marketDetailMessages)) marketDetailMessages[locale].bidCount = bidCount[locale]
