// Country calling codes generated from libphonenumber-js 1.13.13 (Google libphonenumber metadata)
// and region names generated from ICU 78.3 / Unicode CLDR via Intl.DisplayNames.
// Sources: https://github.com/google/libphonenumber and https://cldr.unicode.org/
// Metadata/names are a snapshot; refresh from maintained upstream data when numbering plans change.

export const PHONE_COUNTRIES = [
  {"iso2":"AF","dialCode":"+93","names":{"zh-Hans":"阿富汗","zh-Hant":"阿富汗","en":"Afghanistan","ru":"Афганистан","ja":"アフガニスタン","ko":"아프가니스탄"},"indexLetter":"A"},
  {"iso2":"AX","dialCode":"+358","names":{"zh-Hans":"奥兰群岛","zh-Hant":"奧蘭群島","en":"Åland Islands","ru":"Аландские о-ва","ja":"オーランド諸島","ko":"올란드 제도"},"indexLetter":"A"},
  {"iso2":"AL","dialCode":"+355","names":{"zh-Hans":"阿尔巴尼亚","zh-Hant":"阿爾巴尼亞","en":"Albania","ru":"Албания","ja":"アルバニア","ko":"알바니아"},"indexLetter":"A"},
  {"iso2":"DZ","dialCode":"+213","names":{"zh-Hans":"阿尔及利亚","zh-Hant":"阿爾及利亞","en":"Algeria","ru":"Алжир","ja":"アルジェリア","ko":"알제리"},"indexLetter":"A"},
  {"iso2":"AS","dialCode":"+1","names":{"zh-Hans":"美属萨摩亚","zh-Hant":"美屬薩摩亞","en":"American Samoa","ru":"Американское Самоа","ja":"米領サモア","ko":"아메리칸 사모아"},"indexLetter":"A"},
  {"iso2":"AD","dialCode":"+376","names":{"zh-Hans":"安道尔","zh-Hant":"安道爾","en":"Andorra","ru":"Андорра","ja":"アンドラ","ko":"안도라"},"indexLetter":"A"},
  {"iso2":"AO","dialCode":"+244","names":{"zh-Hans":"安哥拉","zh-Hant":"安哥拉","en":"Angola","ru":"Ангола","ja":"アンゴラ","ko":"앙골라"},"indexLetter":"A"},
  {"iso2":"AI","dialCode":"+1","names":{"zh-Hans":"安圭拉","zh-Hant":"安奎拉","en":"Anguilla","ru":"Ангилья","ja":"アンギラ","ko":"앵귈라"},"indexLetter":"A"},
  {"iso2":"AG","dialCode":"+1","names":{"zh-Hans":"安提瓜和巴布达","zh-Hant":"安地卡及巴布達","en":"Antigua & Barbuda","ru":"Антигуа и Барбуда","ja":"アンティグア・バーブーダ","ko":"앤티가 바부다"},"indexLetter":"A"},
  {"iso2":"AR","dialCode":"+54","names":{"zh-Hans":"阿根廷","zh-Hant":"阿根廷","en":"Argentina","ru":"Аргентина","ja":"アルゼンチン","ko":"아르헨티나"},"indexLetter":"A"},
  {"iso2":"AM","dialCode":"+374","names":{"zh-Hans":"亚美尼亚","zh-Hant":"亞美尼亞","en":"Armenia","ru":"Армения","ja":"アルメニア","ko":"아르메니아"},"indexLetter":"A"},
  {"iso2":"AW","dialCode":"+297","names":{"zh-Hans":"阿鲁巴","zh-Hant":"荷屬阿魯巴","en":"Aruba","ru":"Аруба","ja":"アルバ","ko":"아루바"},"indexLetter":"A"},
  {"iso2":"AC","dialCode":"+247","names":{"zh-Hans":"阿森松岛","zh-Hant":"阿森松島","en":"Ascension Island","ru":"о-в Вознесения","ja":"アセンション島","ko":"어센션섬"},"indexLetter":"A"},
  {"iso2":"AU","dialCode":"+61","names":{"zh-Hans":"澳大利亚","zh-Hant":"澳洲","en":"Australia","ru":"Австралия","ja":"オーストラリア","ko":"오스트레일리아"},"indexLetter":"A"},
  {"iso2":"AT","dialCode":"+43","names":{"zh-Hans":"奥地利","zh-Hant":"奧地利","en":"Austria","ru":"Австрия","ja":"オーストリア","ko":"오스트리아"},"indexLetter":"A"},
  {"iso2":"AZ","dialCode":"+994","names":{"zh-Hans":"阿塞拜疆","zh-Hant":"亞塞拜然","en":"Azerbaijan","ru":"Азербайджан","ja":"アゼルバイジャン","ko":"아제르바이잔"},"indexLetter":"A"},
  {"iso2":"BS","dialCode":"+1","names":{"zh-Hans":"巴哈马","zh-Hant":"巴哈馬","en":"Bahamas","ru":"Багамы","ja":"バハマ","ko":"바하마"},"indexLetter":"B"},
  {"iso2":"BH","dialCode":"+973","names":{"zh-Hans":"巴林","zh-Hant":"巴林","en":"Bahrain","ru":"Бахрейн","ja":"バーレーン","ko":"바레인"},"indexLetter":"B"},
  {"iso2":"BD","dialCode":"+880","names":{"zh-Hans":"孟加拉国","zh-Hant":"孟加拉","en":"Bangladesh","ru":"Бангладеш","ja":"バングラデシュ","ko":"방글라데시"},"indexLetter":"B"},
  {"iso2":"BB","dialCode":"+1","names":{"zh-Hans":"巴巴多斯","zh-Hant":"巴貝多","en":"Barbados","ru":"Барбадос","ja":"バルバドス","ko":"바베이도스"},"indexLetter":"B"},
  {"iso2":"BY","dialCode":"+375","names":{"zh-Hans":"白俄罗斯","zh-Hant":"白俄羅斯","en":"Belarus","ru":"Беларусь","ja":"ベラルーシ","ko":"벨라루스"},"indexLetter":"B"},
  {"iso2":"BE","dialCode":"+32","names":{"zh-Hans":"比利时","zh-Hant":"比利時","en":"Belgium","ru":"Бельгия","ja":"ベルギー","ko":"벨기에"},"indexLetter":"B"},
  {"iso2":"BZ","dialCode":"+501","names":{"zh-Hans":"伯利兹","zh-Hant":"貝里斯","en":"Belize","ru":"Белиз","ja":"ベリーズ","ko":"벨리즈"},"indexLetter":"B"},
  {"iso2":"BJ","dialCode":"+229","names":{"zh-Hans":"贝宁","zh-Hant":"貝南","en":"Benin","ru":"Бенин","ja":"ベナン","ko":"베냉"},"indexLetter":"B"},
  {"iso2":"BM","dialCode":"+1","names":{"zh-Hans":"百慕大","zh-Hant":"百慕達","en":"Bermuda","ru":"Бермудские о-ва","ja":"バミューダ","ko":"버뮤다"},"indexLetter":"B"},
  {"iso2":"BT","dialCode":"+975","names":{"zh-Hans":"不丹","zh-Hant":"不丹","en":"Bhutan","ru":"Бутан","ja":"ブータン","ko":"부탄"},"indexLetter":"B"},
  {"iso2":"BO","dialCode":"+591","names":{"zh-Hans":"玻利维亚","zh-Hant":"玻利維亞","en":"Bolivia","ru":"Боливия","ja":"ボリビア","ko":"볼리비아"},"indexLetter":"B"},
  {"iso2":"BA","dialCode":"+387","names":{"zh-Hans":"波斯尼亚和黑塞哥维那","zh-Hant":"波士尼亞與赫塞哥維納","en":"Bosnia & Herzegovina","ru":"Босния и Герцеговина","ja":"ボスニア・ヘルツェゴビナ","ko":"보스니아 헤르체고비나"},"indexLetter":"B"},
  {"iso2":"BW","dialCode":"+267","names":{"zh-Hans":"博茨瓦纳","zh-Hant":"波札那","en":"Botswana","ru":"Ботсвана","ja":"ボツワナ","ko":"보츠와나"},"indexLetter":"B"},
  {"iso2":"BR","dialCode":"+55","names":{"zh-Hans":"巴西","zh-Hant":"巴西","en":"Brazil","ru":"Бразилия","ja":"ブラジル","ko":"브라질"},"indexLetter":"B"},
  {"iso2":"IO","dialCode":"+246","names":{"zh-Hans":"英属印度洋领地","zh-Hant":"英屬印度洋領地","en":"British Indian Ocean Territory","ru":"Британская территория в Индийском океане","ja":"英領インド洋地域","ko":"영국령 인도양 지역"},"indexLetter":"B"},
  {"iso2":"VG","dialCode":"+1","names":{"zh-Hans":"英属维尔京群岛","zh-Hant":"英屬維京群島","en":"British Virgin Islands","ru":"Виргинские о-ва (Великобритания)","ja":"英領ヴァージン諸島","ko":"영국령 버진아일랜드"},"indexLetter":"B"},
  {"iso2":"BN","dialCode":"+673","names":{"zh-Hans":"文莱","zh-Hant":"汶萊","en":"Brunei","ru":"Бруней","ja":"ブルネイ","ko":"브루나이"},"indexLetter":"B"},
  {"iso2":"BG","dialCode":"+359","names":{"zh-Hans":"保加利亚","zh-Hant":"保加利亞","en":"Bulgaria","ru":"Болгария","ja":"ブルガリア","ko":"불가리아"},"indexLetter":"B"},
  {"iso2":"BF","dialCode":"+226","names":{"zh-Hans":"布基纳法索","zh-Hant":"布吉納法索","en":"Burkina Faso","ru":"Буркина-Фасо","ja":"ブルキナファソ","ko":"부르키나파소"},"indexLetter":"B"},
  {"iso2":"BI","dialCode":"+257","names":{"zh-Hans":"布隆迪","zh-Hant":"蒲隆地","en":"Burundi","ru":"Бурунди","ja":"ブルンジ","ko":"부룬디"},"indexLetter":"B"},
  {"iso2":"KH","dialCode":"+855","names":{"zh-Hans":"柬埔寨","zh-Hant":"柬埔寨","en":"Cambodia","ru":"Камбоджа","ja":"カンボジア","ko":"캄보디아"},"indexLetter":"C"},
  {"iso2":"CM","dialCode":"+237","names":{"zh-Hans":"喀麦隆","zh-Hant":"喀麥隆","en":"Cameroon","ru":"Камерун","ja":"カメルーン","ko":"카메룬"},"indexLetter":"C"},
  {"iso2":"CA","dialCode":"+1","names":{"zh-Hans":"加拿大","zh-Hant":"加拿大","en":"Canada","ru":"Канада","ja":"カナダ","ko":"캐나다"},"indexLetter":"C"},
  {"iso2":"CV","dialCode":"+238","names":{"zh-Hans":"佛得角","zh-Hant":"維德角","en":"Cape Verde","ru":"Кабо-Верде","ja":"カーボベルデ","ko":"카보베르데"},"indexLetter":"C"},
  {"iso2":"BQ","dialCode":"+599","names":{"zh-Hans":"荷属加勒比区","zh-Hant":"荷蘭加勒比區","en":"Caribbean Netherlands","ru":"Бонэйр, Синт-Эстатиус и Саба","ja":"オランダ領カリブ","ko":"네덜란드령 카리브"},"indexLetter":"C"},
  {"iso2":"KY","dialCode":"+1","names":{"zh-Hans":"开曼群岛","zh-Hant":"開曼群島","en":"Cayman Islands","ru":"о-ва Кайман","ja":"ケイマン諸島","ko":"케이맨 제도"},"indexLetter":"C"},
  {"iso2":"CF","dialCode":"+236","names":{"zh-Hans":"中非共和国","zh-Hant":"中非共和國","en":"Central African Republic","ru":"Центрально-Африканская Республика","ja":"中央アフリカ共和国","ko":"중앙 아프리카 공화국"},"indexLetter":"C"},
  {"iso2":"TD","dialCode":"+235","names":{"zh-Hans":"乍得","zh-Hant":"查德","en":"Chad","ru":"Чад","ja":"チャド","ko":"차드"},"indexLetter":"C"},
  {"iso2":"CL","dialCode":"+56","names":{"zh-Hans":"智利","zh-Hant":"智利","en":"Chile","ru":"Чили","ja":"チリ","ko":"칠레"},"indexLetter":"C"},
  {"iso2":"CN","dialCode":"+86","names":{"zh-Hans":"中国","zh-Hant":"中國","en":"China","ru":"Китай","ja":"中国","ko":"중국"},"indexLetter":"C"},
  {"iso2":"CX","dialCode":"+61","names":{"zh-Hans":"圣诞岛","zh-Hant":"聖誕島","en":"Christmas Island","ru":"о-в Рождества","ja":"クリスマス島","ko":"크리스마스섬"},"indexLetter":"C"},
  {"iso2":"CC","dialCode":"+61","names":{"zh-Hans":"科科斯（基林）群岛","zh-Hant":"科克斯（基靈）群島","en":"Cocos (Keeling) Islands","ru":"Кокосовые о-ва","ja":"ココス(キーリング)諸島","ko":"코코스 제도"},"indexLetter":"C"},
  {"iso2":"CO","dialCode":"+57","names":{"zh-Hans":"哥伦比亚","zh-Hant":"哥倫比亞","en":"Colombia","ru":"Колумбия","ja":"コロンビア","ko":"콜롬비아"},"indexLetter":"C"},
  {"iso2":"KM","dialCode":"+269","names":{"zh-Hans":"科摩罗","zh-Hant":"葛摩","en":"Comoros","ru":"Коморы","ja":"コモロ","ko":"코모로"},"indexLetter":"C"},
  {"iso2":"CG","dialCode":"+242","names":{"zh-Hans":"刚果（布）","zh-Hant":"剛果（布拉薩）","en":"Congo - Brazzaville","ru":"Конго - Браззавиль","ja":"コンゴ共和国(ブラザビル)","ko":"콩고-브라자빌"},"indexLetter":"C"},
  {"iso2":"CD","dialCode":"+243","names":{"zh-Hans":"刚果（金）","zh-Hant":"剛果（金夏沙）","en":"Congo - Kinshasa","ru":"Конго - Киншаса","ja":"コンゴ民主共和国(キンシャサ)","ko":"콩고-킨샤사"},"indexLetter":"C"},
  {"iso2":"CK","dialCode":"+682","names":{"zh-Hans":"库克群岛","zh-Hant":"庫克群島","en":"Cook Islands","ru":"о-ва Кука","ja":"クック諸島","ko":"쿡 제도"},"indexLetter":"C"},
  {"iso2":"CR","dialCode":"+506","names":{"zh-Hans":"哥斯达黎加","zh-Hant":"哥斯大黎加","en":"Costa Rica","ru":"Коста-Рика","ja":"コスタリカ","ko":"코스타리카"},"indexLetter":"C"},
  {"iso2":"CI","dialCode":"+225","names":{"zh-Hans":"科特迪瓦","zh-Hant":"象牙海岸","en":"Côte d’Ivoire","ru":"Кот-д’Ивуар","ja":"コートジボワール","ko":"코트디부아르"},"indexLetter":"C"},
  {"iso2":"HR","dialCode":"+385","names":{"zh-Hans":"克罗地亚","zh-Hant":"克羅埃西亞","en":"Croatia","ru":"Хорватия","ja":"クロアチア","ko":"크로아티아"},"indexLetter":"C"},
  {"iso2":"CU","dialCode":"+53","names":{"zh-Hans":"古巴","zh-Hant":"古巴","en":"Cuba","ru":"Куба","ja":"キューバ","ko":"쿠바"},"indexLetter":"C"},
  {"iso2":"CW","dialCode":"+599","names":{"zh-Hans":"库拉索","zh-Hant":"庫拉索","en":"Curaçao","ru":"Кюрасао","ja":"キュラソー","ko":"퀴라소"},"indexLetter":"C"},
  {"iso2":"CY","dialCode":"+357","names":{"zh-Hans":"塞浦路斯","zh-Hant":"賽普勒斯","en":"Cyprus","ru":"Кипр","ja":"キプロス","ko":"키프로스"},"indexLetter":"C"},
  {"iso2":"CZ","dialCode":"+420","names":{"zh-Hans":"捷克","zh-Hant":"捷克","en":"Czechia","ru":"Чехия","ja":"チェコ","ko":"체코"},"indexLetter":"C"},
  {"iso2":"DK","dialCode":"+45","names":{"zh-Hans":"丹麦","zh-Hant":"丹麥","en":"Denmark","ru":"Дания","ja":"デンマーク","ko":"덴마크"},"indexLetter":"D"},
  {"iso2":"DJ","dialCode":"+253","names":{"zh-Hans":"吉布提","zh-Hant":"吉布地","en":"Djibouti","ru":"Джибути","ja":"ジブチ","ko":"지부티"},"indexLetter":"D"},
  {"iso2":"DM","dialCode":"+1","names":{"zh-Hans":"多米尼克","zh-Hant":"多米尼克","en":"Dominica","ru":"Доминика","ja":"ドミニカ国","ko":"도미니카"},"indexLetter":"D"},
  {"iso2":"DO","dialCode":"+1","names":{"zh-Hans":"多米尼加共和国","zh-Hant":"多明尼加共和國","en":"Dominican Republic","ru":"Доминиканская Республика","ja":"ドミニカ共和国","ko":"도미니카 공화국"},"indexLetter":"D"},
  {"iso2":"EC","dialCode":"+593","names":{"zh-Hans":"厄瓜多尔","zh-Hant":"厄瓜多","en":"Ecuador","ru":"Эквадор","ja":"エクアドル","ko":"에콰도르"},"indexLetter":"E"},
  {"iso2":"EG","dialCode":"+20","names":{"zh-Hans":"埃及","zh-Hant":"埃及","en":"Egypt","ru":"Египет","ja":"エジプト","ko":"이집트"},"indexLetter":"E"},
  {"iso2":"SV","dialCode":"+503","names":{"zh-Hans":"萨尔瓦多","zh-Hant":"薩爾瓦多","en":"El Salvador","ru":"Сальвадор","ja":"エルサルバドル","ko":"엘살바도르"},"indexLetter":"E"},
  {"iso2":"GQ","dialCode":"+240","names":{"zh-Hans":"赤道几内亚","zh-Hant":"赤道幾內亞","en":"Equatorial Guinea","ru":"Экваториальная Гвинея","ja":"赤道ギニア","ko":"적도 기니"},"indexLetter":"E"},
  {"iso2":"ER","dialCode":"+291","names":{"zh-Hans":"厄立特里亚","zh-Hant":"厄利垂亞","en":"Eritrea","ru":"Эритрея","ja":"エリトリア","ko":"에리트리아"},"indexLetter":"E"},
  {"iso2":"EE","dialCode":"+372","names":{"zh-Hans":"爱沙尼亚","zh-Hant":"愛沙尼亞","en":"Estonia","ru":"Эстония","ja":"エストニア","ko":"에스토니아"},"indexLetter":"E"},
  {"iso2":"SZ","dialCode":"+268","names":{"zh-Hans":"斯威士兰","zh-Hant":"史瓦帝尼","en":"Eswatini","ru":"Эсватини","ja":"エスワティニ","ko":"에스와티니"},"indexLetter":"E"},
  {"iso2":"ET","dialCode":"+251","names":{"zh-Hans":"埃塞俄比亚","zh-Hant":"衣索比亞","en":"Ethiopia","ru":"Эфиопия","ja":"エチオピア","ko":"에티오피아"},"indexLetter":"E"},
  {"iso2":"FK","dialCode":"+500","names":{"zh-Hans":"福克兰群岛","zh-Hant":"福克蘭群島","en":"Falkland Islands","ru":"Фолклендские о-ва","ja":"フォークランド諸島","ko":"포클랜드 제도"},"indexLetter":"F"},
  {"iso2":"FO","dialCode":"+298","names":{"zh-Hans":"法罗群岛","zh-Hant":"法羅群島","en":"Faroe Islands","ru":"Фарерские о-ва","ja":"フェロー諸島","ko":"페로 제도"},"indexLetter":"F"},
  {"iso2":"FJ","dialCode":"+679","names":{"zh-Hans":"斐济","zh-Hant":"斐濟","en":"Fiji","ru":"Фиджи","ja":"フィジー","ko":"피지"},"indexLetter":"F"},
  {"iso2":"FI","dialCode":"+358","names":{"zh-Hans":"芬兰","zh-Hant":"芬蘭","en":"Finland","ru":"Финляндия","ja":"フィンランド","ko":"핀란드"},"indexLetter":"F"},
  {"iso2":"FR","dialCode":"+33","names":{"zh-Hans":"法国","zh-Hant":"法國","en":"France","ru":"Франция","ja":"フランス","ko":"프랑스"},"indexLetter":"F"},
  {"iso2":"GF","dialCode":"+594","names":{"zh-Hans":"法属圭亚那","zh-Hant":"法屬圭亞那","en":"French Guiana","ru":"Французская Гвиана","ja":"仏領ギアナ","ko":"프랑스령 기아나"},"indexLetter":"F"},
  {"iso2":"PF","dialCode":"+689","names":{"zh-Hans":"法属波利尼西亚","zh-Hant":"法屬玻里尼西亞","en":"French Polynesia","ru":"Французская Полинезия","ja":"仏領ポリネシア","ko":"프랑스령 폴리네시아"},"indexLetter":"F"},
  {"iso2":"GA","dialCode":"+241","names":{"zh-Hans":"加蓬","zh-Hant":"加彭","en":"Gabon","ru":"Габон","ja":"ガボン","ko":"가봉"},"indexLetter":"G"},
  {"iso2":"GM","dialCode":"+220","names":{"zh-Hans":"冈比亚","zh-Hant":"甘比亞","en":"Gambia","ru":"Гамбия","ja":"ガンビア","ko":"감비아"},"indexLetter":"G"},
  {"iso2":"GE","dialCode":"+995","names":{"zh-Hans":"格鲁吉亚","zh-Hant":"喬治亞","en":"Georgia","ru":"Грузия","ja":"ジョージア","ko":"조지아"},"indexLetter":"G"},
  {"iso2":"DE","dialCode":"+49","names":{"zh-Hans":"德国","zh-Hant":"德國","en":"Germany","ru":"Германия","ja":"ドイツ","ko":"독일"},"indexLetter":"G"},
  {"iso2":"GH","dialCode":"+233","names":{"zh-Hans":"加纳","zh-Hant":"迦納","en":"Ghana","ru":"Гана","ja":"ガーナ","ko":"가나"},"indexLetter":"G"},
  {"iso2":"GI","dialCode":"+350","names":{"zh-Hans":"直布罗陀","zh-Hant":"直布羅陀","en":"Gibraltar","ru":"Гибралтар","ja":"ジブラルタル","ko":"지브롤터"},"indexLetter":"G"},
  {"iso2":"GR","dialCode":"+30","names":{"zh-Hans":"希腊","zh-Hant":"希臘","en":"Greece","ru":"Греция","ja":"ギリシャ","ko":"그리스"},"indexLetter":"G"},
  {"iso2":"GL","dialCode":"+299","names":{"zh-Hans":"格陵兰","zh-Hant":"格陵蘭","en":"Greenland","ru":"Гренландия","ja":"グリーンランド","ko":"그린란드"},"indexLetter":"G"},
  {"iso2":"GD","dialCode":"+1","names":{"zh-Hans":"格林纳达","zh-Hant":"格瑞那達","en":"Grenada","ru":"Гренада","ja":"グレナダ","ko":"그레나다"},"indexLetter":"G"},
  {"iso2":"GP","dialCode":"+590","names":{"zh-Hans":"瓜德罗普","zh-Hant":"瓜地洛普","en":"Guadeloupe","ru":"Гваделупа","ja":"グアドループ","ko":"과들루프"},"indexLetter":"G"},
  {"iso2":"GU","dialCode":"+1","names":{"zh-Hans":"关岛","zh-Hant":"關島","en":"Guam","ru":"Гуам","ja":"グアム","ko":"괌"},"indexLetter":"G"},
  {"iso2":"GT","dialCode":"+502","names":{"zh-Hans":"危地马拉","zh-Hant":"瓜地馬拉","en":"Guatemala","ru":"Гватемала","ja":"グアテマラ","ko":"과테말라"},"indexLetter":"G"},
  {"iso2":"GG","dialCode":"+44","names":{"zh-Hans":"根西岛","zh-Hant":"根息","en":"Guernsey","ru":"Гернси","ja":"ガーンジー","ko":"건지"},"indexLetter":"G"},
  {"iso2":"GN","dialCode":"+224","names":{"zh-Hans":"几内亚","zh-Hant":"幾內亞","en":"Guinea","ru":"Гвинея","ja":"ギニア","ko":"기니"},"indexLetter":"G"},
  {"iso2":"GW","dialCode":"+245","names":{"zh-Hans":"几内亚比绍","zh-Hant":"幾內亞比索","en":"Guinea-Bissau","ru":"Гвинея-Бисау","ja":"ギニアビサウ","ko":"기니비사우"},"indexLetter":"G"},
  {"iso2":"GY","dialCode":"+592","names":{"zh-Hans":"圭亚那","zh-Hant":"蓋亞那","en":"Guyana","ru":"Гайана","ja":"ガイアナ","ko":"가이아나"},"indexLetter":"G"},
  {"iso2":"HT","dialCode":"+509","names":{"zh-Hans":"海地","zh-Hant":"海地","en":"Haiti","ru":"Гаити","ja":"ハイチ","ko":"아이티"},"indexLetter":"H"},
  {"iso2":"HN","dialCode":"+504","names":{"zh-Hans":"洪都拉斯","zh-Hant":"宏都拉斯","en":"Honduras","ru":"Гондурас","ja":"ホンジュラス","ko":"온두라스"},"indexLetter":"H"},
  {"iso2":"HK","dialCode":"+852","names":{"zh-Hans":"中国香港特别行政区","zh-Hant":"中國香港特別行政區","en":"Hong Kong SAR China","ru":"Гонконг (САР)","ja":"中華人民共和国香港特別行政区","ko":"홍콩(중국 특별행정구)"},"indexLetter":"H"},
  {"iso2":"HU","dialCode":"+36","names":{"zh-Hans":"匈牙利","zh-Hant":"匈牙利","en":"Hungary","ru":"Венгрия","ja":"ハンガリー","ko":"헝가리"},"indexLetter":"H"},
  {"iso2":"IS","dialCode":"+354","names":{"zh-Hans":"冰岛","zh-Hant":"冰島","en":"Iceland","ru":"Исландия","ja":"アイスランド","ko":"아이슬란드"},"indexLetter":"I"},
  {"iso2":"IN","dialCode":"+91","names":{"zh-Hans":"印度","zh-Hant":"印度","en":"India","ru":"Индия","ja":"インド","ko":"인도"},"indexLetter":"I"},
  {"iso2":"ID","dialCode":"+62","names":{"zh-Hans":"印度尼西亚","zh-Hant":"印尼","en":"Indonesia","ru":"Индонезия","ja":"インドネシア","ko":"인도네시아"},"indexLetter":"I"},
  {"iso2":"IR","dialCode":"+98","names":{"zh-Hans":"伊朗","zh-Hant":"伊朗","en":"Iran","ru":"Иран","ja":"イラン","ko":"이란"},"indexLetter":"I"},
  {"iso2":"IQ","dialCode":"+964","names":{"zh-Hans":"伊拉克","zh-Hant":"伊拉克","en":"Iraq","ru":"Ирак","ja":"イラク","ko":"이라크"},"indexLetter":"I"},
  {"iso2":"IE","dialCode":"+353","names":{"zh-Hans":"爱尔兰","zh-Hant":"愛爾蘭","en":"Ireland","ru":"Ирландия","ja":"アイルランド","ko":"아일랜드"},"indexLetter":"I"},
  {"iso2":"IM","dialCode":"+44","names":{"zh-Hans":"马恩岛","zh-Hant":"曼島","en":"Isle of Man","ru":"о-в Мэн","ja":"マン島","ko":"맨섬"},"indexLetter":"I"},
  {"iso2":"IL","dialCode":"+972","names":{"zh-Hans":"以色列","zh-Hant":"以色列","en":"Israel","ru":"Израиль","ja":"イスラエル","ko":"이스라엘"},"indexLetter":"I"},
  {"iso2":"IT","dialCode":"+39","names":{"zh-Hans":"意大利","zh-Hant":"義大利","en":"Italy","ru":"Италия","ja":"イタリア","ko":"이탈리아"},"indexLetter":"I"},
  {"iso2":"JM","dialCode":"+1","names":{"zh-Hans":"牙买加","zh-Hant":"牙買加","en":"Jamaica","ru":"Ямайка","ja":"ジャマイカ","ko":"자메이카"},"indexLetter":"J"},
  {"iso2":"JP","dialCode":"+81","names":{"zh-Hans":"日本","zh-Hant":"日本","en":"Japan","ru":"Япония","ja":"日本","ko":"일본"},"indexLetter":"J"},
  {"iso2":"JE","dialCode":"+44","names":{"zh-Hans":"泽西岛","zh-Hant":"澤西島","en":"Jersey","ru":"Джерси","ja":"ジャージー","ko":"저지"},"indexLetter":"J"},
  {"iso2":"JO","dialCode":"+962","names":{"zh-Hans":"约旦","zh-Hant":"約旦","en":"Jordan","ru":"Иордания","ja":"ヨルダン","ko":"요르단"},"indexLetter":"J"},
  {"iso2":"KZ","dialCode":"+7","names":{"zh-Hans":"哈萨克斯坦","zh-Hant":"哈薩克","en":"Kazakhstan","ru":"Казахстан","ja":"カザフスタン","ko":"카자흐스탄"},"indexLetter":"K"},
  {"iso2":"KE","dialCode":"+254","names":{"zh-Hans":"肯尼亚","zh-Hant":"肯亞","en":"Kenya","ru":"Кения","ja":"ケニア","ko":"케냐"},"indexLetter":"K"},
  {"iso2":"KI","dialCode":"+686","names":{"zh-Hans":"基里巴斯","zh-Hant":"吉里巴斯","en":"Kiribati","ru":"Кирибати","ja":"キリバス","ko":"키리바시"},"indexLetter":"K"},
  {"iso2":"XK","dialCode":"+383","names":{"zh-Hans":"科索沃","zh-Hant":"科索沃","en":"Kosovo","ru":"Косово","ja":"コソボ","ko":"코소보"},"indexLetter":"K"},
  {"iso2":"KW","dialCode":"+965","names":{"zh-Hans":"科威特","zh-Hant":"科威特","en":"Kuwait","ru":"Кувейт","ja":"クウェート","ko":"쿠웨이트"},"indexLetter":"K"},
  {"iso2":"KG","dialCode":"+996","names":{"zh-Hans":"吉尔吉斯斯坦","zh-Hant":"吉爾吉斯","en":"Kyrgyzstan","ru":"Киргизия","ja":"キルギス","ko":"키르기스스탄"},"indexLetter":"K"},
  {"iso2":"LA","dialCode":"+856","names":{"zh-Hans":"老挝","zh-Hant":"寮國","en":"Laos","ru":"Лаос","ja":"ラオス","ko":"라오스"},"indexLetter":"L"},
  {"iso2":"LV","dialCode":"+371","names":{"zh-Hans":"拉脱维亚","zh-Hant":"拉脫維亞","en":"Latvia","ru":"Латвия","ja":"ラトビア","ko":"라트비아"},"indexLetter":"L"},
  {"iso2":"LB","dialCode":"+961","names":{"zh-Hans":"黎巴嫩","zh-Hant":"黎巴嫩","en":"Lebanon","ru":"Ливан","ja":"レバノン","ko":"레바논"},"indexLetter":"L"},
  {"iso2":"LS","dialCode":"+266","names":{"zh-Hans":"莱索托","zh-Hant":"賴索托","en":"Lesotho","ru":"Лесото","ja":"レソト","ko":"레소토"},"indexLetter":"L"},
  {"iso2":"LR","dialCode":"+231","names":{"zh-Hans":"利比里亚","zh-Hant":"賴比瑞亞","en":"Liberia","ru":"Либерия","ja":"リベリア","ko":"라이베리아"},"indexLetter":"L"},
  {"iso2":"LY","dialCode":"+218","names":{"zh-Hans":"利比亚","zh-Hant":"利比亞","en":"Libya","ru":"Ливия","ja":"リビア","ko":"리비아"},"indexLetter":"L"},
  {"iso2":"LI","dialCode":"+423","names":{"zh-Hans":"列支敦士登","zh-Hant":"列支敦斯登","en":"Liechtenstein","ru":"Лихтенштейн","ja":"リヒテンシュタイン","ko":"리히텐슈타인"},"indexLetter":"L"},
  {"iso2":"LT","dialCode":"+370","names":{"zh-Hans":"立陶宛","zh-Hant":"立陶宛","en":"Lithuania","ru":"Литва","ja":"リトアニア","ko":"리투아니아"},"indexLetter":"L"},
  {"iso2":"LU","dialCode":"+352","names":{"zh-Hans":"卢森堡","zh-Hant":"盧森堡","en":"Luxembourg","ru":"Люксембург","ja":"ルクセンブルク","ko":"룩셈부르크"},"indexLetter":"L"},
  {"iso2":"MO","dialCode":"+853","names":{"zh-Hans":"中国澳门特别行政区","zh-Hant":"中國澳門特別行政區","en":"Macao SAR China","ru":"Макао (САР)","ja":"中華人民共和国マカオ特別行政区","ko":"마카오(중국 특별행정구)"},"indexLetter":"M"},
  {"iso2":"MG","dialCode":"+261","names":{"zh-Hans":"马达加斯加","zh-Hant":"馬達加斯加","en":"Madagascar","ru":"Мадагаскар","ja":"マダガスカル","ko":"마다가스카르"},"indexLetter":"M"},
  {"iso2":"MW","dialCode":"+265","names":{"zh-Hans":"马拉维","zh-Hant":"馬拉威","en":"Malawi","ru":"Малави","ja":"マラウイ","ko":"말라위"},"indexLetter":"M"},
  {"iso2":"MY","dialCode":"+60","names":{"zh-Hans":"马来西亚","zh-Hant":"馬來西亞","en":"Malaysia","ru":"Малайзия","ja":"マレーシア","ko":"말레이시아"},"indexLetter":"M"},
  {"iso2":"MV","dialCode":"+960","names":{"zh-Hans":"马尔代夫","zh-Hant":"馬爾地夫","en":"Maldives","ru":"Мальдивы","ja":"モルディブ","ko":"몰디브"},"indexLetter":"M"},
  {"iso2":"ML","dialCode":"+223","names":{"zh-Hans":"马里","zh-Hant":"馬利","en":"Mali","ru":"Мали","ja":"マリ","ko":"말리"},"indexLetter":"M"},
  {"iso2":"MT","dialCode":"+356","names":{"zh-Hans":"马耳他","zh-Hant":"馬爾他","en":"Malta","ru":"Мальта","ja":"マルタ","ko":"몰타"},"indexLetter":"M"},
  {"iso2":"MH","dialCode":"+692","names":{"zh-Hans":"马绍尔群岛","zh-Hant":"馬紹爾群島","en":"Marshall Islands","ru":"Маршалловы о-ва","ja":"マーシャル諸島","ko":"마셜 제도"},"indexLetter":"M"},
  {"iso2":"MQ","dialCode":"+596","names":{"zh-Hans":"马提尼克","zh-Hant":"馬丁尼克","en":"Martinique","ru":"Мартиника","ja":"マルティニーク","ko":"마르티니크"},"indexLetter":"M"},
  {"iso2":"MR","dialCode":"+222","names":{"zh-Hans":"毛里塔尼亚","zh-Hant":"茅利塔尼亞","en":"Mauritania","ru":"Мавритания","ja":"モーリタニア","ko":"모리타니"},"indexLetter":"M"},
  {"iso2":"MU","dialCode":"+230","names":{"zh-Hans":"毛里求斯","zh-Hant":"模里西斯","en":"Mauritius","ru":"Маврикий","ja":"モーリシャス","ko":"모리셔스"},"indexLetter":"M"},
  {"iso2":"YT","dialCode":"+262","names":{"zh-Hans":"马约特","zh-Hant":"馬約特島","en":"Mayotte","ru":"Майотта","ja":"マヨット","ko":"마요트"},"indexLetter":"M"},
  {"iso2":"MX","dialCode":"+52","names":{"zh-Hans":"墨西哥","zh-Hant":"墨西哥","en":"Mexico","ru":"Мексика","ja":"メキシコ","ko":"멕시코"},"indexLetter":"M"},
  {"iso2":"FM","dialCode":"+691","names":{"zh-Hans":"密克罗尼西亚","zh-Hant":"密克羅尼西亞","en":"Micronesia","ru":"Федеративные Штаты Микронезии","ja":"ミクロネシア連邦","ko":"미크로네시아"},"indexLetter":"M"},
  {"iso2":"MD","dialCode":"+373","names":{"zh-Hans":"摩尔多瓦","zh-Hant":"摩爾多瓦","en":"Moldova","ru":"Молдова","ja":"モルドバ","ko":"몰도바"},"indexLetter":"M"},
  {"iso2":"MC","dialCode":"+377","names":{"zh-Hans":"摩纳哥","zh-Hant":"摩納哥","en":"Monaco","ru":"Монако","ja":"モナコ","ko":"모나코"},"indexLetter":"M"},
  {"iso2":"MN","dialCode":"+976","names":{"zh-Hans":"蒙古","zh-Hant":"蒙古","en":"Mongolia","ru":"Монголия","ja":"モンゴル","ko":"몽골"},"indexLetter":"M"},
  {"iso2":"ME","dialCode":"+382","names":{"zh-Hans":"黑山","zh-Hant":"蒙特內哥羅","en":"Montenegro","ru":"Черногория","ja":"モンテネグロ","ko":"몬테네그로"},"indexLetter":"M"},
  {"iso2":"MS","dialCode":"+1","names":{"zh-Hans":"蒙特塞拉特","zh-Hant":"蒙哲臘","en":"Montserrat","ru":"Монтсеррат","ja":"モントセラト","ko":"몬트세라트"},"indexLetter":"M"},
  {"iso2":"MA","dialCode":"+212","names":{"zh-Hans":"摩洛哥","zh-Hant":"摩洛哥","en":"Morocco","ru":"Марокко","ja":"モロッコ","ko":"모로코"},"indexLetter":"M"},
  {"iso2":"MZ","dialCode":"+258","names":{"zh-Hans":"莫桑比克","zh-Hant":"莫三比克","en":"Mozambique","ru":"Мозамбик","ja":"モザンビーク","ko":"모잠비크"},"indexLetter":"M"},
  {"iso2":"MM","dialCode":"+95","names":{"zh-Hans":"缅甸","zh-Hant":"緬甸","en":"Myanmar (Burma)","ru":"Мьянма (Бирма)","ja":"ミャンマー (ビルマ)","ko":"미얀마"},"indexLetter":"M"},
  {"iso2":"NA","dialCode":"+264","names":{"zh-Hans":"纳米比亚","zh-Hant":"納米比亞","en":"Namibia","ru":"Намибия","ja":"ナミビア","ko":"나미비아"},"indexLetter":"N"},
  {"iso2":"NR","dialCode":"+674","names":{"zh-Hans":"瑙鲁","zh-Hant":"諾魯","en":"Nauru","ru":"Науру","ja":"ナウル","ko":"나우루"},"indexLetter":"N"},
  {"iso2":"NP","dialCode":"+977","names":{"zh-Hans":"尼泊尔","zh-Hant":"尼泊爾","en":"Nepal","ru":"Непал","ja":"ネパール","ko":"네팔"},"indexLetter":"N"},
  {"iso2":"NL","dialCode":"+31","names":{"zh-Hans":"荷兰","zh-Hant":"荷蘭","en":"Netherlands","ru":"Нидерланды","ja":"オランダ","ko":"네덜란드"},"indexLetter":"N"},
  {"iso2":"NC","dialCode":"+687","names":{"zh-Hans":"新喀里多尼亚","zh-Hant":"新喀里多尼亞","en":"New Caledonia","ru":"Новая Каледония","ja":"ニューカレドニア","ko":"뉴칼레도니아"},"indexLetter":"N"},
  {"iso2":"NZ","dialCode":"+64","names":{"zh-Hans":"新西兰","zh-Hant":"紐西蘭","en":"New Zealand","ru":"Новая Зеландия","ja":"ニュージーランド","ko":"뉴질랜드"},"indexLetter":"N"},
  {"iso2":"NI","dialCode":"+505","names":{"zh-Hans":"尼加拉瓜","zh-Hant":"尼加拉瓜","en":"Nicaragua","ru":"Никарагуа","ja":"ニカラグア","ko":"니카라과"},"indexLetter":"N"},
  {"iso2":"NE","dialCode":"+227","names":{"zh-Hans":"尼日尔","zh-Hant":"尼日","en":"Niger","ru":"Нигер","ja":"ニジェール","ko":"니제르"},"indexLetter":"N"},
  {"iso2":"NG","dialCode":"+234","names":{"zh-Hans":"尼日利亚","zh-Hant":"奈及利亞","en":"Nigeria","ru":"Нигерия","ja":"ナイジェリア","ko":"나이지리아"},"indexLetter":"N"},
  {"iso2":"NU","dialCode":"+683","names":{"zh-Hans":"纽埃","zh-Hant":"紐埃島","en":"Niue","ru":"Ниуэ","ja":"ニウエ","ko":"니우에"},"indexLetter":"N"},
  {"iso2":"NF","dialCode":"+672","names":{"zh-Hans":"诺福克岛","zh-Hant":"諾福克島","en":"Norfolk Island","ru":"о-в Норфолк","ja":"ノーフォーク島","ko":"노퍽섬"},"indexLetter":"N"},
  {"iso2":"KP","dialCode":"+850","names":{"zh-Hans":"朝鲜","zh-Hant":"北韓","en":"North Korea","ru":"КНДР","ja":"北朝鮮","ko":"북한"},"indexLetter":"N"},
  {"iso2":"MK","dialCode":"+389","names":{"zh-Hans":"北马其顿","zh-Hant":"北馬其頓","en":"North Macedonia","ru":"Северная Македония","ja":"北マケドニア","ko":"북마케도니아"},"indexLetter":"N"},
  {"iso2":"MP","dialCode":"+1","names":{"zh-Hans":"北马里亚纳群岛","zh-Hant":"北馬利安納群島","en":"Northern Mariana Islands","ru":"Северные Марианские о-ва","ja":"北マリアナ諸島","ko":"북마리아나제도"},"indexLetter":"N"},
  {"iso2":"NO","dialCode":"+47","names":{"zh-Hans":"挪威","zh-Hant":"挪威","en":"Norway","ru":"Норвегия","ja":"ノルウェー","ko":"노르웨이"},"indexLetter":"N"},
  {"iso2":"OM","dialCode":"+968","names":{"zh-Hans":"阿曼","zh-Hant":"阿曼","en":"Oman","ru":"Оман","ja":"オマーン","ko":"오만"},"indexLetter":"O"},
  {"iso2":"PK","dialCode":"+92","names":{"zh-Hans":"巴基斯坦","zh-Hant":"巴基斯坦","en":"Pakistan","ru":"Пакистан","ja":"パキスタン","ko":"파키스탄"},"indexLetter":"P"},
  {"iso2":"PW","dialCode":"+680","names":{"zh-Hans":"帕劳","zh-Hant":"帛琉","en":"Palau","ru":"Палау","ja":"パラオ","ko":"팔라우"},"indexLetter":"P"},
  {"iso2":"PS","dialCode":"+970","names":{"zh-Hans":"巴勒斯坦领土","zh-Hant":"巴勒斯坦自治區","en":"Palestinian Territories","ru":"Палестинские территории","ja":"パレスチナ自治区","ko":"팔레스타인 지구"},"indexLetter":"P"},
  {"iso2":"PA","dialCode":"+507","names":{"zh-Hans":"巴拿马","zh-Hant":"巴拿馬","en":"Panama","ru":"Панама","ja":"パナマ","ko":"파나마"},"indexLetter":"P"},
  {"iso2":"PG","dialCode":"+675","names":{"zh-Hans":"巴布亚新几内亚","zh-Hant":"巴布亞紐幾內亞","en":"Papua New Guinea","ru":"Папуа — Новая Гвинея","ja":"パプアニューギニア","ko":"파푸아뉴기니"},"indexLetter":"P"},
  {"iso2":"PY","dialCode":"+595","names":{"zh-Hans":"巴拉圭","zh-Hant":"巴拉圭","en":"Paraguay","ru":"Парагвай","ja":"パラグアイ","ko":"파라과이"},"indexLetter":"P"},
  {"iso2":"PE","dialCode":"+51","names":{"zh-Hans":"秘鲁","zh-Hant":"秘魯","en":"Peru","ru":"Перу","ja":"ペルー","ko":"페루"},"indexLetter":"P"},
  {"iso2":"PH","dialCode":"+63","names":{"zh-Hans":"菲律宾","zh-Hant":"菲律賓","en":"Philippines","ru":"Филиппины","ja":"フィリピン","ko":"필리핀"},"indexLetter":"P"},
  {"iso2":"PL","dialCode":"+48","names":{"zh-Hans":"波兰","zh-Hant":"波蘭","en":"Poland","ru":"Польша","ja":"ポーランド","ko":"폴란드"},"indexLetter":"P"},
  {"iso2":"PT","dialCode":"+351","names":{"zh-Hans":"葡萄牙","zh-Hant":"葡萄牙","en":"Portugal","ru":"Португалия","ja":"ポルトガル","ko":"포르투갈"},"indexLetter":"P"},
  {"iso2":"PR","dialCode":"+1","names":{"zh-Hans":"波多黎各","zh-Hant":"波多黎各","en":"Puerto Rico","ru":"Пуэрто-Рико","ja":"プエルトリコ","ko":"푸에르토리코"},"indexLetter":"P"},
  {"iso2":"QA","dialCode":"+974","names":{"zh-Hans":"卡塔尔","zh-Hant":"卡達","en":"Qatar","ru":"Катар","ja":"カタール","ko":"카타르"},"indexLetter":"Q"},
  {"iso2":"RE","dialCode":"+262","names":{"zh-Hans":"留尼汪","zh-Hant":"留尼旺","en":"Réunion","ru":"Реюньон","ja":"レユニオン","ko":"레위니옹"},"indexLetter":"R"},
  {"iso2":"RO","dialCode":"+40","names":{"zh-Hans":"罗马尼亚","zh-Hant":"羅馬尼亞","en":"Romania","ru":"Румыния","ja":"ルーマニア","ko":"루마니아"},"indexLetter":"R"},
  {"iso2":"RU","dialCode":"+7","names":{"zh-Hans":"俄罗斯","zh-Hant":"俄羅斯","en":"Russia","ru":"Россия","ja":"ロシア","ko":"러시아"},"indexLetter":"R"},
  {"iso2":"RW","dialCode":"+250","names":{"zh-Hans":"卢旺达","zh-Hant":"盧安達","en":"Rwanda","ru":"Руанда","ja":"ルワンダ","ko":"르완다"},"indexLetter":"R"},
  {"iso2":"WS","dialCode":"+685","names":{"zh-Hans":"萨摩亚","zh-Hant":"薩摩亞","en":"Samoa","ru":"Самоа","ja":"サモア","ko":"사모아"},"indexLetter":"S"},
  {"iso2":"SM","dialCode":"+378","names":{"zh-Hans":"圣马力诺","zh-Hant":"聖馬利諾","en":"San Marino","ru":"Сан-Марино","ja":"サンマリノ","ko":"산마리노"},"indexLetter":"S"},
  {"iso2":"ST","dialCode":"+239","names":{"zh-Hans":"圣多美和普林西比","zh-Hant":"聖多美普林西比","en":"São Tomé & Príncipe","ru":"Сан-Томе и Принсипи","ja":"サントメ・プリンシペ","ko":"상투메 프린시페"},"indexLetter":"S"},
  {"iso2":"SA","dialCode":"+966","names":{"zh-Hans":"沙特阿拉伯","zh-Hant":"沙烏地阿拉伯","en":"Saudi Arabia","ru":"Саудовская Аравия","ja":"サウジアラビア","ko":"사우디아라비아"},"indexLetter":"S"},
  {"iso2":"SN","dialCode":"+221","names":{"zh-Hans":"塞内加尔","zh-Hant":"塞內加爾","en":"Senegal","ru":"Сенегал","ja":"セネガル","ko":"세네갈"},"indexLetter":"S"},
  {"iso2":"RS","dialCode":"+381","names":{"zh-Hans":"塞尔维亚","zh-Hant":"塞爾維亞","en":"Serbia","ru":"Сербия","ja":"セルビア","ko":"세르비아"},"indexLetter":"S"},
  {"iso2":"SC","dialCode":"+248","names":{"zh-Hans":"塞舌尔","zh-Hant":"塞席爾","en":"Seychelles","ru":"Сейшельские о-ва","ja":"セーシェル","ko":"세이셸"},"indexLetter":"S"},
  {"iso2":"SL","dialCode":"+232","names":{"zh-Hans":"塞拉利昂","zh-Hant":"獅子山","en":"Sierra Leone","ru":"Сьерра-Леоне","ja":"シエラレオネ","ko":"시에라리온"},"indexLetter":"S"},
  {"iso2":"SG","dialCode":"+65","names":{"zh-Hans":"新加坡","zh-Hant":"新加坡","en":"Singapore","ru":"Сингапур","ja":"シンガポール","ko":"싱가포르"},"indexLetter":"S"},
  {"iso2":"SX","dialCode":"+1","names":{"zh-Hans":"荷属圣马丁","zh-Hant":"荷屬聖馬丁","en":"Sint Maarten","ru":"Синт-Мартен","ja":"シント・マールテン","ko":"신트마르턴"},"indexLetter":"S"},
  {"iso2":"SK","dialCode":"+421","names":{"zh-Hans":"斯洛伐克","zh-Hant":"斯洛伐克","en":"Slovakia","ru":"Словакия","ja":"スロバキア","ko":"슬로바키아"},"indexLetter":"S"},
  {"iso2":"SI","dialCode":"+386","names":{"zh-Hans":"斯洛文尼亚","zh-Hant":"斯洛維尼亞","en":"Slovenia","ru":"Словения","ja":"スロベニア","ko":"슬로베니아"},"indexLetter":"S"},
  {"iso2":"SB","dialCode":"+677","names":{"zh-Hans":"所罗门群岛","zh-Hant":"索羅門群島","en":"Solomon Islands","ru":"Соломоновы о-ва","ja":"ソロモン諸島","ko":"솔로몬 제도"},"indexLetter":"S"},
  {"iso2":"SO","dialCode":"+252","names":{"zh-Hans":"索马里","zh-Hant":"索馬利亞","en":"Somalia","ru":"Сомали","ja":"ソマリア","ko":"소말리아"},"indexLetter":"S"},
  {"iso2":"ZA","dialCode":"+27","names":{"zh-Hans":"南非","zh-Hant":"南非","en":"South Africa","ru":"Южно-Африканская Республика","ja":"南アフリカ","ko":"남아프리카"},"indexLetter":"S"},
  {"iso2":"KR","dialCode":"+82","names":{"zh-Hans":"韩国","zh-Hant":"南韓","en":"South Korea","ru":"Республика Корея","ja":"韓国","ko":"대한민국"},"indexLetter":"S"},
  {"iso2":"SS","dialCode":"+211","names":{"zh-Hans":"南苏丹","zh-Hant":"南蘇丹","en":"South Sudan","ru":"Южный Судан","ja":"南スーダン","ko":"남수단"},"indexLetter":"S"},
  {"iso2":"ES","dialCode":"+34","names":{"zh-Hans":"西班牙","zh-Hant":"西班牙","en":"Spain","ru":"Испания","ja":"スペイン","ko":"스페인"},"indexLetter":"S"},
  {"iso2":"LK","dialCode":"+94","names":{"zh-Hans":"斯里兰卡","zh-Hant":"斯里蘭卡","en":"Sri Lanka","ru":"Шри-Ланка","ja":"スリランカ","ko":"스리랑카"},"indexLetter":"S"},
  {"iso2":"BL","dialCode":"+590","names":{"zh-Hans":"圣巴泰勒米","zh-Hant":"聖巴瑟米","en":"St. Barthélemy","ru":"Сен-Бартелеми","ja":"サン・バルテルミー","ko":"생바르텔레미"},"indexLetter":"S"},
  {"iso2":"SH","dialCode":"+290","names":{"zh-Hans":"圣赫勒拿","zh-Hant":"聖赫勒拿島","en":"St. Helena","ru":"о-в Св. Елены","ja":"セントヘレナ","ko":"세인트헬레나"},"indexLetter":"S"},
  {"iso2":"KN","dialCode":"+1","names":{"zh-Hans":"圣基茨和尼维斯","zh-Hant":"聖克里斯多福及尼維斯","en":"St. Kitts & Nevis","ru":"Сент-Китс и Невис","ja":"セントクリストファー・ネーヴィス","ko":"세인트키츠 네비스"},"indexLetter":"S"},
  {"iso2":"LC","dialCode":"+1","names":{"zh-Hans":"圣卢西亚","zh-Hant":"聖露西亞","en":"St. Lucia","ru":"Сент-Люсия","ja":"セントルシア","ko":"세인트루시아"},"indexLetter":"S"},
  {"iso2":"MF","dialCode":"+590","names":{"zh-Hans":"法属圣马丁","zh-Hant":"法屬聖馬丁","en":"St. Martin","ru":"Сен-Мартен","ja":"サン・マルタン","ko":"생마르탱"},"indexLetter":"S"},
  {"iso2":"PM","dialCode":"+508","names":{"zh-Hans":"圣皮埃尔和密克隆群岛","zh-Hant":"聖皮埃與密克隆群島","en":"St. Pierre & Miquelon","ru":"Сен-Пьер и Микелон","ja":"サンピエール島・ミクロン島","ko":"생피에르 미클롱"},"indexLetter":"S"},
  {"iso2":"VC","dialCode":"+1","names":{"zh-Hans":"圣文森特和格林纳丁斯","zh-Hant":"聖文森及格瑞那丁","en":"St. Vincent & Grenadines","ru":"Сент-Винсент и Гренадины","ja":"セントビンセント及びグレナディーン諸島","ko":"세인트빈센트그레나딘"},"indexLetter":"S"},
  {"iso2":"SD","dialCode":"+249","names":{"zh-Hans":"苏丹","zh-Hant":"蘇丹","en":"Sudan","ru":"Судан","ja":"スーダン","ko":"수단"},"indexLetter":"S"},
  {"iso2":"SR","dialCode":"+597","names":{"zh-Hans":"苏里南","zh-Hant":"蘇利南","en":"Suriname","ru":"Суринам","ja":"スリナム","ko":"수리남"},"indexLetter":"S"},
  {"iso2":"SJ","dialCode":"+47","names":{"zh-Hans":"斯瓦尔巴和扬马延","zh-Hant":"挪威屬斯瓦巴及尖棉","en":"Svalbard & Jan Mayen","ru":"Шпицберген и Ян-Майен","ja":"スバールバル諸島・ヤンマイエン島","ko":"스발바르제도-얀마웬섬"},"indexLetter":"S"},
  {"iso2":"SE","dialCode":"+46","names":{"zh-Hans":"瑞典","zh-Hant":"瑞典","en":"Sweden","ru":"Швеция","ja":"スウェーデン","ko":"스웨덴"},"indexLetter":"S"},
  {"iso2":"CH","dialCode":"+41","names":{"zh-Hans":"瑞士","zh-Hant":"瑞士","en":"Switzerland","ru":"Швейцария","ja":"スイス","ko":"스위스"},"indexLetter":"S"},
  {"iso2":"SY","dialCode":"+963","names":{"zh-Hans":"叙利亚","zh-Hant":"敘利亞","en":"Syria","ru":"Сирия","ja":"シリア","ko":"시리아"},"indexLetter":"S"},
  {"iso2":"TW","dialCode":"+886","names":{"zh-Hans":"台湾","zh-Hant":"台灣","en":"Taiwan","ru":"Тайвань","ja":"台湾","ko":"대만"},"indexLetter":"T"},
  {"iso2":"TJ","dialCode":"+992","names":{"zh-Hans":"塔吉克斯坦","zh-Hant":"塔吉克","en":"Tajikistan","ru":"Таджикистан","ja":"タジキスタン","ko":"타지키스탄"},"indexLetter":"T"},
  {"iso2":"TZ","dialCode":"+255","names":{"zh-Hans":"坦桑尼亚","zh-Hant":"坦尚尼亞","en":"Tanzania","ru":"Танзания","ja":"タンザニア","ko":"탄자니아"},"indexLetter":"T"},
  {"iso2":"TH","dialCode":"+66","names":{"zh-Hans":"泰国","zh-Hant":"泰國","en":"Thailand","ru":"Таиланд","ja":"タイ","ko":"태국"},"indexLetter":"T"},
  {"iso2":"TL","dialCode":"+670","names":{"zh-Hans":"东帝汶","zh-Hant":"東帝汶","en":"Timor-Leste","ru":"Восточный Тимор","ja":"東ティモール","ko":"동티모르"},"indexLetter":"T"},
  {"iso2":"TG","dialCode":"+228","names":{"zh-Hans":"多哥","zh-Hant":"多哥","en":"Togo","ru":"Того","ja":"トーゴ","ko":"토고"},"indexLetter":"T"},
  {"iso2":"TK","dialCode":"+690","names":{"zh-Hans":"托克劳","zh-Hant":"托克勞群島","en":"Tokelau","ru":"Токелау","ja":"トケラウ","ko":"토켈라우"},"indexLetter":"T"},
  {"iso2":"TO","dialCode":"+676","names":{"zh-Hans":"汤加","zh-Hant":"東加","en":"Tonga","ru":"Тонга","ja":"トンガ","ko":"통가"},"indexLetter":"T"},
  {"iso2":"TT","dialCode":"+1","names":{"zh-Hans":"特立尼达和多巴哥","zh-Hant":"千里達及托巴哥","en":"Trinidad & Tobago","ru":"Тринидад и Тобаго","ja":"トリニダード・トバゴ","ko":"트리니다드 토바고"},"indexLetter":"T"},
  {"iso2":"TA","dialCode":"+290","names":{"zh-Hans":"特里斯坦-达库尼亚群岛","zh-Hant":"特里斯坦達庫尼亞群島","en":"Tristan da Cunha","ru":"Тристан-да-Кунья","ja":"トリスタン・ダ・クーニャ","ko":"트리스탄다쿠나"},"indexLetter":"T"},
  {"iso2":"TN","dialCode":"+216","names":{"zh-Hans":"突尼斯","zh-Hant":"突尼西亞","en":"Tunisia","ru":"Тунис","ja":"チュニジア","ko":"튀니지"},"indexLetter":"T"},
  {"iso2":"TR","dialCode":"+90","names":{"zh-Hans":"土耳其","zh-Hant":"土耳其","en":"Türkiye","ru":"Турция","ja":"トルコ","ko":"튀르키예"},"indexLetter":"T"},
  {"iso2":"TM","dialCode":"+993","names":{"zh-Hans":"土库曼斯坦","zh-Hant":"土庫曼","en":"Turkmenistan","ru":"Туркменистан","ja":"トルクメニスタン","ko":"투르크메니스탄"},"indexLetter":"T"},
  {"iso2":"TC","dialCode":"+1","names":{"zh-Hans":"特克斯和凯科斯群岛","zh-Hant":"土克斯及開科斯群島","en":"Turks & Caicos Islands","ru":"Тёркс и Кайкос","ja":"タークス・カイコス諸島","ko":"터크스 케이커스 제도"},"indexLetter":"T"},
  {"iso2":"TV","dialCode":"+688","names":{"zh-Hans":"图瓦卢","zh-Hant":"吐瓦魯","en":"Tuvalu","ru":"Тувалу","ja":"ツバル","ko":"투발루"},"indexLetter":"T"},
  {"iso2":"VI","dialCode":"+1","names":{"zh-Hans":"美属维尔京群岛","zh-Hant":"美屬維京群島","en":"U.S. Virgin Islands","ru":"Виргинские о-ва (США)","ja":"米領ヴァージン諸島","ko":"미국령 버진아일랜드"},"indexLetter":"U"},
  {"iso2":"UG","dialCode":"+256","names":{"zh-Hans":"乌干达","zh-Hant":"烏干達","en":"Uganda","ru":"Уганда","ja":"ウガンダ","ko":"우간다"},"indexLetter":"U"},
  {"iso2":"UA","dialCode":"+380","names":{"zh-Hans":"乌克兰","zh-Hant":"烏克蘭","en":"Ukraine","ru":"Украина","ja":"ウクライナ","ko":"우크라이나"},"indexLetter":"U"},
  {"iso2":"AE","dialCode":"+971","names":{"zh-Hans":"阿拉伯联合酋长国","zh-Hant":"阿拉伯聯合大公國","en":"United Arab Emirates","ru":"ОАЭ","ja":"アラブ首長国連邦","ko":"아랍에미리트"},"indexLetter":"U"},
  {"iso2":"GB","dialCode":"+44","names":{"zh-Hans":"英国","zh-Hant":"英國","en":"United Kingdom","ru":"Великобритания","ja":"イギリス","ko":"영국"},"indexLetter":"U"},
  {"iso2":"US","dialCode":"+1","names":{"zh-Hans":"美国","zh-Hant":"美國","en":"United States","ru":"Соединенные Штаты","ja":"アメリカ合衆国","ko":"미국"},"indexLetter":"U"},
  {"iso2":"UY","dialCode":"+598","names":{"zh-Hans":"乌拉圭","zh-Hant":"烏拉圭","en":"Uruguay","ru":"Уругвай","ja":"ウルグアイ","ko":"우루과이"},"indexLetter":"U"},
  {"iso2":"UZ","dialCode":"+998","names":{"zh-Hans":"乌兹别克斯坦","zh-Hant":"烏茲別克","en":"Uzbekistan","ru":"Узбекистан","ja":"ウズベキスタン","ko":"우즈베키스탄"},"indexLetter":"U"},
  {"iso2":"VU","dialCode":"+678","names":{"zh-Hans":"瓦努阿图","zh-Hant":"萬那杜","en":"Vanuatu","ru":"Вануату","ja":"バヌアツ","ko":"바누아투"},"indexLetter":"V"},
  {"iso2":"VA","dialCode":"+39","names":{"zh-Hans":"梵蒂冈","zh-Hant":"梵蒂岡","en":"Vatican City","ru":"Ватикан","ja":"バチカン市国","ko":"바티칸 시국"},"indexLetter":"V"},
  {"iso2":"VE","dialCode":"+58","names":{"zh-Hans":"委内瑞拉","zh-Hant":"委內瑞拉","en":"Venezuela","ru":"Венесуэла","ja":"ベネズエラ","ko":"베네수엘라"},"indexLetter":"V"},
  {"iso2":"VN","dialCode":"+84","names":{"zh-Hans":"越南","zh-Hant":"越南","en":"Vietnam","ru":"Вьетнам","ja":"ベトナム","ko":"베트남"},"indexLetter":"V"},
  {"iso2":"WF","dialCode":"+681","names":{"zh-Hans":"瓦利斯和富图纳","zh-Hant":"瓦利斯群島和富圖那群島","en":"Wallis & Futuna","ru":"Уоллис и Футуна","ja":"ウォリス・フツナ","ko":"왈리스-푸투나 제도"},"indexLetter":"W"},
  {"iso2":"EH","dialCode":"+212","names":{"zh-Hans":"西撒哈拉","zh-Hant":"西撒哈拉","en":"Western Sahara","ru":"Западная Сахара","ja":"西サハラ","ko":"서사하라"},"indexLetter":"W"},
  {"iso2":"YE","dialCode":"+967","names":{"zh-Hans":"也门","zh-Hant":"葉門","en":"Yemen","ru":"Йемен","ja":"イエメン","ko":"예멘"},"indexLetter":"Y"},
  {"iso2":"ZM","dialCode":"+260","names":{"zh-Hans":"赞比亚","zh-Hant":"尚比亞","en":"Zambia","ru":"Замбия","ja":"ザンビア","ko":"잠비아"},"indexLetter":"Z"},
  {"iso2":"ZW","dialCode":"+263","names":{"zh-Hans":"津巴布韦","zh-Hant":"辛巴威","en":"Zimbabwe","ru":"Зимбабве","ja":"ジンバブエ","ko":"짐바브웨"},"indexLetter":"Z"},
]

const SEARCH_ALIASES = {
  CN: ['mainland china', 'prc', 'zhongguo'],
  GB: ['uk', 'britain', 'yingguo'],
  HK: ['hongkong', 'xianggang'],
  JP: ['riben'],
  KR: ['south korea', 'hanguk', 'hanguo'],
  MO: ['macau', 'aomen'],
  RU: ['russia', 'eluosi'],
  TW: ['taiwan'],
  US: ['usa', 'america', 'meiguo']
}

function normalizePhoneCountrySearch(value) {
  const text = String(value || '').trim().toLowerCase()
  const folded = typeof text.normalize === 'function'
    ? text.normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    : text
  return folded.replace(/[\s+().,'’&\-_\/，、·（）]/g, '')
}

export function getPhoneCountryName(country, locale = 'en') {
  if (!country) return ''
  const resolvedLocale = locale === 'zh-CN' || locale === 'zh' ? 'zh-Hans'
    : locale === 'zh-TW' || locale === 'zh-HK' ? 'zh-Hant'
      : locale
  return (country.names && (country.names[resolvedLocale] || country.names.en)) || country.iso2 || ''
}

export function getPhoneCountryIndexLetter(country) {
  return country && country.indexLetter ? country.indexLetter : '#'
}

export function filterPhoneCountries(query, locale = 'en') {
  const needle = normalizePhoneCountrySearch(query)
  if (!needle) return PHONE_COUNTRIES
  if (/^\+?\d+$/.test(String(query).trim())) {
    return PHONE_COUNTRIES.filter(country => country.dialCode.slice(1).startsWith(needle))
  }
  return PHONE_COUNTRIES.filter(country => {
    const names = country.names || {}
    const terms = [
      country.iso2, country.dialCode, getPhoneCountryName(country, locale),
      names.en, names['zh-Hans'], names['zh-Hant'], names.ru, names.ja, names.ko,
      ...(SEARCH_ALIASES[country.iso2] || [])
    ]
    return terms.some(term => normalizePhoneCountrySearch(term).includes(needle))
  })
}
