const keys=['all','chat','trade','reminders','myTrades','buying','selling','bidding','intent','awaiting_buyer','agreed','buyer_paid','paid','shipped','completed','cancelled','disputed','auction_won','expired','expiring','unsold','consulting','order','conversation','delivery','shipping','pickup','note','intentSubmit','accept','confirm','mark_paid','confirm_paid','ship','receive','cancel','help','amount','shippingInfo','reason','manualPayment','confirmAction','send','empty','failed','retry','viewOrder','viewItem','history','remaining','messages','contact','buy','newMessage','bidResult','details','close','loading','submit','unavailable'];
const rows={
'zh-Hans':['全部','聊天','交易','交易提醒','我的交易','我的购买','我的出售','我的竞拍','待卖家确认','待买家确认','已确认成交','买家已标记付款','卖家已确认收款','待收货','已完成','已取消','协助处理中','你已中拍，等待确认','确认超时，交易取消','即将超过确认期限','拍卖流拍','咨询中','交易详情','商品沟通','交付方式','邮寄','同城自提','给卖家留言','提交购买意向','确认意向及价格','确认购买','标记已付款','确认收到款项','填写交付信息','确认收货','取消交易','申请协助','成交金额','物流单号或交付说明','请填写原因','平台暂不代收款。付款状态由交易双方确认。','确认执行此操作？请核实交易信息。','发送','暂无记录','操作失败，请重试','重试','查看交易详情','查看商品','操作记录','剩余确认时间','消息','联系卖家','意向购买','新消息','竞拍结果','商品资料','关闭','加载中…','提交','当前商品或状态不可操作，请刷新后查看'],
'zh-Hant':['全部','聊天','交易','交易提醒','我的交易','我的購買','我的出售','我的競拍','待賣家確認','待買家確認','已確認成交','買家已標記付款','賣家已確認收款','待收貨','已完成','已取消','協助處理中','你已中拍，等待確認','確認逾時，交易取消','即將超過確認期限','拍賣流拍','諮詢中','交易詳情','商品溝通','交付方式','郵寄','同城自提','給賣家留言','提交購買意向','確認意向及價格','確認購買','標記已付款','確認收到款項','填寫交付資訊','確認收貨','取消交易','申請協助','成交金額','物流單號或交付說明','請填寫原因','平台暫不代收款。付款狀態由交易雙方確認。','確認執行此操作？請核實交易資訊。','傳送','暫無紀錄','操作失敗，請重試','重試','查看交易詳情','查看商品','操作紀錄','剩餘確認時間','消息','聯絡賣家','意向購買','新消息','競拍結果','商品資料','關閉','載入中…','提交','目前商品或狀態不可操作，請重新整理後查看'],
en:['All','Chats','Trade','Trade updates','My trades','Purchases','Sales','My auctions','Awaiting seller','Awaiting buyer','Deal confirmed','Buyer marked paid','Seller confirmed receipt','Awaiting delivery','Completed','Cancelled','Assistance requested','Auction won; confirm purchase','Confirmation expired; cancelled','Confirmation deadline approaching','No winning bid','Enquiry','Trade details','Item conversation','Delivery','Shipping','Local pickup','Message to seller','Submit interest','Accept and set price','Confirm purchase','Mark as paid','Confirm funds received','Add delivery details','Confirm delivery','Cancel trade','Request assistance','Agreed price','Tracking or handover details','Enter a reason','The platform does not collect payments. Payment status is confirmed by the parties.','Confirm this action? Please check the trade details.','Send','No records yet','Could not complete. Try again.','Retry','View trade','View item','Activity','Time to confirm','Messages','Contact seller','Interested','New message','Auction result','Item details','Close','Loading…','Submit','Item or status unavailable. Refresh to see the latest state.'],
ru:['Все','Чаты','Сделки','Уведомления','Мои сделки','Покупки','Продажи','Мои торги','Ожидает продавца','Ожидает покупателя','Сделка подтверждена','Покупатель отметил оплату','Продавец подтвердил получение','Ожидает получения','Завершено','Отменено','Запрошена помощь','Торги выиграны: подтвердите','Срок подтверждения истёк','Срок подтверждения истекает','Нет победителя','Консультация','Детали сделки','Чат о товаре','Получение','Доставка','Самовывоз','Сообщение продавцу','Оставить заявку','Принять и указать цену','Подтвердить покупку','Отметить оплату','Подтвердить получение денег','Указать доставку','Подтвердить получение','Отменить сделку','Запросить помощь','Цена сделки','Номер отправления или описание передачи','Укажите причину','Платформа не принимает платежи. Статус подтверждают стороны.','Подтвердить действие? Проверьте сведения.','Отправить','Записей нет','Не удалось. Повторите попытку.','Повторить','Открыть сделку','Открыть товар','История','До подтверждения','Сообщения','Связаться','Хочу купить','Новое сообщение','Итог торгов','Сведения','Закрыть','Загрузка…','Отправить','Товар или действие недоступны. Обновите страницу.'],
ja:['すべて','チャット','取引','取引通知','マイ取引','購入','販売','入札した商品','出品者の確認待ち','購入者の確認待ち','取引確定','購入者が支払を申告','出品者が入金を確認','受取待ち','完了','キャンセル','サポート対応中','落札しました。購入確認へ','確認期限切れでキャンセル','確認期限が近づいています','落札者なし','相談中','取引詳細','商品チャット','受渡方法','配送','直接受取','出品者へのメッセージ','購入希望を送信','承認して価格設定','購入を確認','支払済みを申告','入金を確認','配送情報を入力','受取を確認','取引をキャンセル','サポート依頼','取引価格','追跡番号・受渡内容','理由を入力','プラットフォームは代金を受領しません。支払状況は当事者が確認します。','この操作を確定しますか？内容をご確認ください。','送信','履歴はありません','操作できませんでした。再試行してください。','再試行','取引を見る','商品を見る','操作履歴','確認期限まで','メッセージ','出品者に連絡','購入希望','新着メッセージ','落札結果','商品情報','閉じる','読込中…','送信','商品または操作が利用できません。更新してください。'],
ko:['전체','채팅','거래','거래 알림','내 거래','구매','판매','내 입찰','판매자 확인 대기','구매자 확인 대기','거래 확정','구매자가 결제 표시','판매자가 입금 확인','수령 대기','완료','취소','지원 요청됨','낙찰되었습니다. 구매를 확인하세요','확인 기한 만료로 취소','확인 기한 임박','낙찰자 없음','상담 중','거래 상세','상품 대화','배송 방법','택배','직거래','판매자에게 메시지','구매 의사 보내기','수락 및 가격 설정','구매 확인','결제 완료 표시','입금 확인','전달 정보 입력','수령 확인','거래 취소','도움 요청','거래 금액','운송장 또는 전달 내용','사유를 입력하세요','플랫폼은 대금을 수령하지 않습니다. 결제 상태는 당사자가 확인합니다.','진행하시겠습니까? 거래 정보를 확인하세요.','보내기','기록 없음','처리하지 못했습니다. 다시 시도하세요.','다시 시도','거래 보기','상품 보기','활동 기록','확인까지 남은 시간','메시지','판매자 연락','구매 의사','새 메시지','입찰 결과','상품 정보','닫기','불러오는 중…','제출','상품이나 상태를 사용할 수 없습니다. 새로고침하세요.']};
export const tradeMessages=Object.fromEntries(Object.entries(rows).map(([locale,values])=>[locale,Object.fromEntries(keys.map((key,index)=>[key,values[index]]))]));
const imageLabels={'zh-Hans':'[图片]','zh-Hant':'[圖片]',en:'[Image]',ru:'[Изображение]',ja:'[画像]',ko:'[사진]'};
for(const locale of Object.keys(tradeMessages))tradeMessages[locale].image=imageLabels[locale];
