<template>
  <swiper class="feed" vertical :current="current" @change="current=$event.detail.current"><swiper-item v-for="post in posts" :key="post.id"><view class="item"><swiper class="photos" circular><swiper-item v-for="src in post.images" :key="src"><image class="photo" :src="src" mode="aspectFit" @click="onPhotoTap(post)"/></swiper-item></swiper><view class="meta"><text class="name">{{ post.title }}</text><text>¥ {{ post.price }}</text><view><text @click="like(post)">{{ post.isLiked ? '♥' : '♡' }} {{ post.likeCount }}</text><text class="comment" @click="openComments(post)">评论 {{ post.commentCount }}</text></view></view></view></swiper-item></swiper>
  <view v-if="commentPost" class="comment-mask" @click.self="commentPost = null"><view class="comment-panel"><view class="comment-header"><text>评论 {{ commentPost.commentCount }}</text><text @click="commentPost = null">×</text></view><scroll-view scroll-y class="comment-list"><view v-for="comment in comments" :key="comment.id" class="comment-row"><text class="comment-author">{{ comment.author_name || '用户' }}</text><text>{{ comment.content }}</text></view><view v-if="!comments.length" class="comment-empty">还没有评论，来说第一句吧</view></scroll-view><view class="comment-input"><input v-model="commentText" placeholder="说点什么…" confirm-type="send" @confirm="sendComment"/><text @click="sendComment">发送</text></view></view></view>
</template>
<script setup>
import { ref } from 'vue'; import { onLoad } from '@dcloudio/uni-app'; import { addMarketCommentApi, getMarketCommentsApi, getMarketPostsApi, toggleMarketLikeApi } from '@/api/market.js'
const posts=ref([]), current=ref(0), commentPost=ref(null), commentText=ref(''), comments=ref([]); let lastTap=0
onLoad(async o=>{ const d=await getMarketPostsApi({category:o.category}); posts.value=d?.posts||[]; current.value=Math.max(0,posts.value.findIndex(p=>String(p.id)===String(o.postId))) })
async function like(post){const old={isLiked:post.isLiked,likeCount:post.likeCount};post.isLiked=!old.isLiked;post.likeCount+=post.isLiked?1:-1;try{Object.assign(post,await toggleMarketLikeApi(post.id))}catch(e){Object.assign(post,old)}}
function onPhotoTap(post){const now=Date.now();if(now-lastTap<280) like(post);lastTap=now}
async function openComments(post){commentPost.value=post;commentText.value='';try{const data=await getMarketCommentsApi(post.id);comments.value=data?.comments||[]}catch(e){comments.value=[];uni.showToast({title:e?.error||'评论加载失败',icon:'none'})}}
async function sendComment(){const text=commentText.value.trim();if(!text)return;const post=commentPost.value;try{await addMarketCommentApi(post.id,{content:text});post.commentCount++;commentText.value='';const data=await getMarketCommentsApi(post.id);comments.value=data?.comments||[]}catch(e){uni.showToast({title:e?.error||'评论发送失败',icon:'none'})}}
</script>
<style scoped>.feed{height:100vh;background:#111}.item{height:100vh;display:flex;flex-direction:column}.photos{height:76vh}.photo{width:100%;height:100%}.meta{color:#fff;padding:28rpx;display:flex;flex-direction:column;gap:18rpx}.name{font-size:38rpx;font-weight:700}.comment{margin-left:36rpx}.comment-mask{position:fixed;inset:0;z-index:10;display:flex;align-items:flex-end;background:rgba(0,0,0,.35)}.comment-panel{width:100%;padding:24rpx;box-sizing:border-box;border-radius:28rpx 28rpx 0 0;background:#fff}.comment-header,.comment-input{display:flex;justify-content:space-between;align-items:center}.comment-list{max-height:48vh;margin:22rpx 0}.comment-row{display:flex;gap:12rpx;padding:16rpx 0}.comment-author{font-weight:700;color:#6d5300}.comment-empty{padding:46rpx 0;text-align:center;color:#999}.comment-input{gap:20rpx}.comment-input input{background:#f4f4f4;flex:1;padding:18rpx;border-radius:12rpx}</style>
